### ISSUE TITLE
[WAGON-276] Read timed out during release:perform after updating to Maven 2.2

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#196]
**[Dennis Kieselhorst](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=deki)** opened **[WAGON-276](https://issues.apache.org/jira/browse/WAGON-276?redirect=false)** and commented

Artifact deployment fails with Maven 2.2:

```
[INFO] [DEBUG] Read timed out
[INFO] java.net.SocketTimeoutException: Read timed out
[INFO]  at java.net.SocketInputStream.socketRead0(Native Method)
[INFO]  at java.net.SocketInputStream.read(SocketInputStream.java:129)
[INFO]  at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
[INFO]  at java.io.BufferedInputStream.read(BufferedInputStream.java:237)
[INFO]  at hidden.org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
[INFO]  at hidden.org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
[INFO]  at hidden.org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
[INFO]  at hidden.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
[INFO]  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
[INFO]  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:446)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:330)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:280)
[INFO]  at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:262)
[INFO]  at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:172)
[INFO]  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107)
[INFO]  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:173)
[INFO]  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
[INFO]  at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:597)
[INFO]  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
[INFO]  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
[INFO]  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
[INFO]  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] BUILD ERROR
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Error deploying artifact: Read timed out
[INFO]
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [DEBUG] Trace
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: Read timed out
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:703)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
[INFO]  at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:41)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:597)
[INFO]  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
[INFO]  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
[INFO]  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
[INFO]  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: Read timed out
[INFO]  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:195)
[INFO]  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
[INFO]  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
[INFO]  ... 17 more
[INFO] Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: Read timed out
[INFO]  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:121)
[INFO]  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:173)
[INFO]  ... 19 more
[INFO] Caused by: org.apache.maven.wagon.TransferFailedException: Read timed out
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:336)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:280)
[INFO]  at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:262)
[INFO]  at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:172)
[INFO]  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:107)
[INFO]  ... 20 more
[INFO] Caused by: java.net.SocketTimeoutException: Read timed out
[INFO]  at java.net.SocketInputStream.socketRead0(Native Method)
[INFO]  at java.net.SocketInputStream.read(SocketInputStream.java:129)
[INFO]  at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
[INFO]  at java.io.BufferedInputStream.read(BufferedInputStream.java:237)
[INFO]  at hidden.org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
[INFO]  at hidden.org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
[INFO]  at hidden.org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
[INFO]  at hidden.org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
[INFO]  at hidden.org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
[INFO]  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
[INFO]  at hidden.org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:446)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:330)
[INFO]  ... 24 more
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 1 minute 53 seconds
[INFO] [INFO] Finished at: Mon Jul 20 16:43:21 CEST 2009
[INFO] [INFO] Final Memory: 39M/254M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Maven execution failed, exit code: '1'
```

With Maven 2.1 there is only a small warning (there is a mod_rewrite rule in the apache httpd configuration):

```
[INFO] 20.07.2009 16:03:37 hidden.org.apache.commons.httpclient.HttpMethodBase processCookieHeaders
[INFO] WARNUNG: Cookie rejected: "$Version=0; JSESSIONID=F6397CEA0440E28D3606D82DF7E73B07; $Path=/archiva". Illegal path attribute "/archiva". Path of origin: "/repository/......
```

Repository server is Archiva 1.2.1 (Tomcat 6.0.18/ HTTPD 2.2.3).

---
No further details from [WAGON-276](https://issues.apache.org/jira/browse/WAGON-276?redirect=false)

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

Hi! Could you please retest this with wagon-http 2.0-SNASHOT? We moved this over from commons.httpclient to apache.httpcomponents.client.

\<build>
\<extensions>
\<extension>
\<groupId>org.apache.maven.wagon\</groupId>
\<artifactId>wagon-http\</artifactId>
\<version>2.0-SNAPSHOT\</version>
\</extension>
\</extensions>
\</build>
