### ISSUE TITLE
[WAGON-124] wagon-http dos not handle HTTP 204 No Content code as success

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#214]
**[Matthew Daniel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdaniel)** opened **[WAGON-124](https://issues.apache.org/jira/browse/WAGON-124?redirect=false)** and commented

q.v. HTTP RFC 2616 section 9.6 "PUT": "If an existing resource is modified,
either the 200 (OK) or 204 (No Content) response codes SHOULD be sent
to indicate successful completion of the request."

Currently:

org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:160)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error installing artifact's metadata: Error while deploying metadata: Failed to transfer file: http://servername/path/to/my/artifactid/maven-metadata.xml. Return code is: 204
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:99)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:148)
... 18 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataDeploymentException: Error while deploying metadata: Failed to transfer file: http://servername/path/to/my/artifactid/maven-metadata.xml. Return code is: 204
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:433)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:83)
... 19 more
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://servername/path/to/my/artifactid/maven-metadata.xml. Return code is: 204
at org.apache.maven.wagon.providers.http.HttpWagon.put(HttpWagon.java:209)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:180)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifactMetadata(DefaultWagonManager.java:116)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:429)
... 20 more

---

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** commented

This work has apparently already been done.

The following codes are considered Success in wagon-http-lightweight and wagon-http providers.

* 200 - OK
* 201 - Created
* 202 - Accepted
* 204 - No Content
