### ISSUE TITLE
[WAGON-154] A space in an artifact name produces the error "TransferFailedException: scp: ambiguous target"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#234]
**[Sean Kelly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kelly)** opened **[WAGON-154](https://issues.apache.org/jira/browse/WAGON-154?redirect=false)** and commented

I'm deploying an artifact using the <artifact:deploy> tag. The artifact name has a space in it:

<artifact:deploy artifact='Mac OS X Installer.dmg' ... />

This is to an "scp://" style repository.  This produces the following stack trace:

Failed to deploy to: oodt Reason: org.apache.maven.wagon.TransferFailedException: scp: ambiguous target

org.apache.maven.wagon.TransferFailedException: scp: ambiguous target

    at org.apache.maven.wagon.providers.ssh.ScpWagon.checkAck(ScpWagon.java:650)
    at org.apache.maven.wagon.providers.ssh.ScpWagon.put(ScpWagon.java:273)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deployFiles(DefaultArtifactDeployer.java:371)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.doDeploy(DefaultArtifactDeployer.java:310)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.handleDeploy(DefaultArtifactDeployer.java:120)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:88)
    at org.apache.maven.artifact.deployer.DeployBean.deploy(DeployBean.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:324)
    at org.apache.commons.jelly.impl.DynamicBeanTag.doTag(DynamicBeanTag.java:180)
    at org.apache.commons.jelly.impl.StaticTagScript.run(StaticTagScript.java:102)
    at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    at org.apache.commons.jelly.impl.DynamicTag.doTag(DynamicTag.java:79)
    at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:247)
    at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    at org.apache.maven.jelly.tags.werkz.MavenGoalTag.runBodyTag(MavenGoalTag.java:78)
    at org.apache.maven.jelly.tags.werkz.MavenGoalTag$MavenGoalAction.performAction(MavenGoalTag.java:109)
    at org.apache.maven.werkz.Goal.fire(Goal.java:656)
    at org.apache.maven.werkz.Goal.attain(Goal.java:592)
    at org.apache.maven.werkz.WerkzProject.attainGoal(WerkzProject.java:210)
    at org.apache.maven.jelly.tags.werkz.MavenAttainGoalTag.doTag(MavenAttainGoalTag.java:114)
    at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:247)
    at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    at org.apache.commons.jelly.TagSupport.invokeBody(TagSupport.java:186)
    at org.apache.commons.jelly.tags.core.IfTag.doTag(IfTag.java:42)
    at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:247)
    at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    at org.apache.maven.jelly.tags.werkz.MavenGoalTag.runBodyTag(MavenGoalTag.java:78)
    at org.apache.maven.jelly.tags.werkz.MavenGoalTag$MavenGoalAction.performAction(MavenGoalTag.java:109)
    at org.apache.maven.werkz.Goal.fire(Goal.java:656)
    at org.apache.maven.werkz.Goal.attain(Goal.java:592)
    at org.apache.maven.plugin.PluginManager.attainGoals(PluginManager.java:693)
    at org.apache.maven.MavenSession.attainGoals(MavenSession.java:263)
    at org.apache.maven.cli.App.doMain(App.java:511)
    at org.apache.maven.cli.App.main(App.java:1258)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:324)
    at com.werken.forehead.Forehead.run(Forehead.java:551)
    at com.werken.forehead.Forehead.main(Forehead.java:581)

Unfortunately, JSCH's ChannelExec takes only a string and not an array of Strings that could be discrete command-line arguments.  Perhaps quoting the artifact name when you build the command-line would fix it?

---

**Issue Links:**
- [MNG-1131](https://issues.apache.org/jira/browse/MNG-1131) address necessary wagon issues
 (_**"is depended upon by"**_)

**Comment by jira-importer** [comment]
**[Sean Kelly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kelly)** commented

Oops; I didn't mean to leave this at the default priority "Major".  It's minor.  A workaround is just to use scpexe:// instead.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

added test case, but can't be reproduced. If this doesn't work for you after the next release / from SVN, please reopen with more details. ambiguous target might be because of a space in the remote repo url instead?
