### ISSUE TITLE
[WAGON-64] File cannot be created error...

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#252]
**[Caleb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caleb.lyness)** opened **[WAGON-64](https://issues.apache.org/jira/browse/WAGON-64?redirect=false)** and commented

I am using maven 1.0 to build and deploy. As of a couple of days back I started getting deploy problems.
I am completely lost as to explain the error and desperately would like some one to shed some light
I am deploying to maven repository which lives in a windows share.

The repository is defined as follows in the project.properties file:

maven.repo.list=internal
maven.repo.internal=file://
maven.repo.internal.directory=\\\\192.168.150.7\\Maven.Internal.Repo

This has been working for nearly a year now. (An aside any other arrangment of URL sepecification always results
in the deployment to the local host... yes I have tried all combinations and read the stuff out there. Makes no difference)

It now fails with the following error:

Will deploy to 1 repository(ies): internal
Deploying to repository: internal
Uploading to System/poms/Service-1.4.0.pom:
.................... (6K)
Failed to deploy to: internal Reason: org.apache.maven.wagon.TransferFailedException: Specified destination directory cannot be created: \\192.168.150.7\Maven.Internal.Repo\System\poms
org.apache.maven.wagon.TransferFailedException: Specified destination directory cannot be created: \\192.168.150.7\Maven.Internal.Repo\System\poms
at org.apache.maven.wagon.AbstractWagon.createParentDirectories(AbstractWagon.java:169)
at org.apache.maven.wagon.providers.file.FileWagon.fillOutputData(FileWagon.java:82)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:133)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deployFiles(DefaultArtifactDeployer.java:407)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.doDeploy(DefaultArtifactDeployer.java:324)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.handleDeploy(DefaultArtifactDeployer.java:131)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:102)
at org.apache.maven.artifact.deployer.DeployBean.deploy(DeployBean.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

Notice how the first upload worked. While the second one dies while trying to create the parent directly (which does exist).
The first upload must have executed exactly the same code!

I have updated wagon jars the plugin is using and this does not modify the error.

in AbstractWagon.java the failing code is:
protected void createParentDirectories(File destination)
throws TransferFailedException
{
File destinationDirectory = destination.getParentFile();
if(destinationDirectory != null && !destinationDirectory.exists() && !destinationDirectory.mkdirs())
throw new TransferFailedException("Specified destination directory cannot be created: " + destinationDirectory);
else
return;
}

I wrote a quick test which runs on the same machine:

     System.out.println("Test: ");
     File destination = new File("\\\\192.168.150.7\\Maven.Internal.Repo\\System\\poms\\test-file"); 
    File destinationDirectory = destination.getParentFile();
    if  (destinationDirectory != null 
       && !destinationDirectory.exists() 
       && !destinationDirectory.mkdirs())
             System.out.println("Failed!");
    else
             System.out.println("Ok!");
    destination.createNewFile();
    if  (destinationDirectory != null 
                 && !destinationDirectory.exists() 
                 && !destinationDirectory.mkdirs())
                       System.out.println("Failed!");
          else
                       System.out.println("Ok!");

This works fine. I get an empty file on the share.

---

**Affects:** 1.0-alpha-2, 1.0-alpha-3, 1.0-alpha-4, 1.0-alpha-5, 1.0-alpha-6, 1.0-alpha-7

**Attachments:**
- [diff.txt](https://issues.apache.org/jira/secure/attachment/12720757/diff.txt) (_1.64 kB_)

**Comment by jira-importer** [comment]
**[Caleb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caleb.lyness)** commented

I updated to the latest version: 1.0-beta-1, inserted some println in the org.apache.maven.wagon.AbstractWagon.createParentDirectories and reran deployment. Here is the output:

Will deploy to 1 repository(ies): internal
Deploying to repository: internal
Uploading to System/poms/Service-1.4.0.pom:
Destination file: \\192.168.150.7\Maven.Internal.Repo\System\poms\Service-1.4.0.pom
Destination directory: \\192.168.150.7\Maven.Internal.Repo\System\poms
Directory exists (or not specified)
.................... (6K)
Destination file: \\192.168.150.7\Maven.Internal.Repo\System\poms\Service-1.4.0.pom.md5
Destination directory: \\192.168.150.7\Maven.Internal.Repo\System\poms
Destination does not exist... create it...
Failed to deploy to: internal Reason: org.apache.maven.wagon.TransferFailedException: Specified dest
ination directory cannot be created: \\192.168.150.7\Maven.Internal.Repo\System\poms
org.apache.maven.wagon.TransferFailedException: Specified destination directory cannot be created: \
\192.168.150.7\Maven.Internal.Repo\System\poms
at org.apache.maven.wagon.AbstractWagon.createParentDirectories(AbstractWagon.java:172)
at org.apache.maven.wagon.providers.file.FileWagon.fillOutputData(FileWagon.java:82)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:133)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deployFiles(DefaultArtifactDep

Here is the code I changed with printlns

    protected void createParentDirectories( File destination )
        throws TransferFailedException
    {
        System.out.println("Destination file: "+destination);
        File destinationDirectory = destination.getParentFile();
        System.out.println("Destination directory: "+destinationDirectory);
        if ( destinationDirectory != null && !destinationDirectory.exists() )
        {
          System.out.println("Destination does not exist... create it...");          
            if ( !destinationDirectory.mkdirs() )
            {                
                throw new TransferFailedException(
                    "Specified destination directory cannot be created: " + destinationDirectory );
            } else {
              System.out.println("Directory created");
            }
        } else {
            System.out.println("Directory exists (or not specified)");          
        }
    }

**Comment by jira-importer** [comment]
**[Caleb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caleb.lyness)** commented

And again....

When I use jdb and step through the code the problem does not occur. Race condition perhaps?
If I just run using jdb the problem still occurs.

I added some more code, which now checks if the directory actually exists
before continuing further. Now the directory does exist and
everything carries on happily.

    protected void createParentDirectories( File destination )
        throws TransferFailedException
    {
        System.out.println("Destination file: "+destination);
        File destinationDirectory = destination.getParentFile();
        System.out.println("Destination directory: "+destinationDirectory);
        if ( destinationDirectory != null && !destinationDirectory.exists() )
        {
          System.out.println("Destination does not exist... create it...");          
            if ( !destinationDirectory.mkdirs() )
            {
            	if (destinationDirectory.exists()) {
            	    System.out.println("mkdirs failed. But directory exists...");	
            	} else {
            		System.out.println("Failed to create file:"+destinationDirectory);
            		System.out.println("Problem ignored");
            		
                //throw new TransferFailedException(
                //    "Specified destination directory cannot be created: " + destinationDirectory );
            	}
            } else {
              System.out.println("Directory created");
            }
        } else {
            System.out.println("Directory exists (or not specified)");          
        }
    }

Why does the first check fail and the second not?????

**Comment by jira-importer** [comment]
**[Caleb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caleb.lyness)** commented

One step further.... using SysInternals File Monitor:

05:51:28 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        Options: Open  Access: All
05:51:28 PM QUERY INFORMATION \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        FileNetworkOpenInformation
05:51:28 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        
05:51:28 PM CREATE            \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom  SUCCESS        Options: OverwriteIf  Access: All
05:51:28 PM WRITE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom  SUCCESS        Offset: 0 Length: 4096
05:51:29 PM WRITE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom  SUCCESS        Offset: 4096 Length: 2078
05:51:29 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom  SUCCESS        
05:51:29 PM QUERY INFORMATION C:\Home\Caleb\.maven\cache\maven-license-plugin-1.2\org\codehaus\plexus\util\FileUtils.class PATH NOT FOUND  Attributes: Error
05:51:29 PM READ              C:\Home\Caleb\.maven\repository\plexus\jars\plexus-utils-1.0-alpha-3.jar   SUCCESS        Offset: 96572 Length: 30
05:51:29 PM READ              C:\Home\Caleb\.maven\repository\plexus\jars\plexus-utils-1.0-alpha-3.jar   SUCCESS        Offset: 96602 Length: 40
05:51:29 PM READ              C:\Home\Caleb\.maven\repository\plexus\jars\plexus-utils-1.0-alpha-3.jar   SUCCESS        Offset: 96642 Length: 8063

------------- Here comes the problem ---------------

05:51:29 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\poms                            BAD NETWORK PATH              Options: Open  Access: All
------------- Here the problem is "gone" ---------------

05:51:29 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        Options: Open  Access: All
05:51:30 PM QUERY INFORMATION \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        FileNetworkOpenInformation
05:51:30 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        
05:51:30 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        Options: Open  Access: All
05:51:30 PM QUERY INFORMATION \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        FileNetworkOpenInformation
05:51:30 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        
05:51:30 PM CREATE            \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom.md5 SUCCESS     Options: OverwriteIf  Access: All
05:51:30 PM WRITE             WRITE                                                                      SUCCESS        Offset: 0 Length: 32
05:51:30 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom.md5 SUCCESS     
05:51:30 PM READ              C:                                                                         SUCCESS        Offset: 112521216 Length: 4096
05:51:30 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        Options: Open  Access: All
05:51:30 PM QUERY INFORMATION \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        FileNetworkOpenInformation
05:51:30 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms                            SUCCESS        
05:51:30 PM CREATE            \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom.sha1  SUCCESS   Options: OverwriteIf  Access: All
05:51:31 PM WRITE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom.sha1  SUCCESS   Offset: 0 Length: 40
05:51:31 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\poms\EZPaySMSService-1.4.0.pom.sha1  SUCCESS      
05:51:31 PM OPEN              \\192.168.150.7\Maven.Internal.Repo\System\wars                            SUCCESS        Options: Open  Access: All
05:51:31 PM QUERY INFORMATION \\192.168.150.7\Maven.Internal.Repo\System\wars                            SUCCESS        FileNetworkOpenInformation
05:51:31 PM CLOSE             \\192.168.150.7\Maven.Internal.Repo\System\wars                            SUCCESS

So now we know what is happening lower down. Notice the time stamps. We are talking millseconds here. I can't explain why a BAD NETWORK PATH error occurs. This is the end of the bug track from me. I have not been able to reproduce this exact problem outside of maven/wagon.... are there any smart people out there can suggest something?

**Comment by jira-importer** [comment]
**[Brian Lowe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=benefitfocus)** commented

Caleb, I started seeing that same issue recently, but not in maven. I'm making a direct call to org.apache.commons.io.FileUtils.copyFile() and the copy operation fails randomly on different subsystems with the "directory cannot be created" error. Did you ever find a solution? I wonder if it is related to a Windows update since ours also worked flawlessly for months then broke with no changes to the code.

**Comment by jira-importer** [comment]
**[Caleb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=caleb.lyness)** commented

Added the diff as an attachment. Because of formatting issues...
