### ISSUE TITLE
[WAGON-70] Deploying using scp:// hangs when proxy configured in settings.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#255]
**[Stephen Coy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sfcoy)** opened **[WAGON-70](https://issues.apache.org/jira/browse/WAGON-70?redirect=false)** and commented

For some reason, wagon-ssh is attempting to connect to the proxy defined in settings.xml (irrespective of whether it is enabled or not) in order to perform an scp transfer.

This causes goals such as site:deploy to hang for some time before proceeding normally.

A thread dump taken during the hang:

[INFO] [site:deploy]
Full thread dump Java HotSpot(TM) Client VM (1.4.2_13-b06 mixed mode):

"Signal Dispatcher" daemon prio=10 tid=0x009cf600 nid=0xa7c waiting on condition [0x00000000..0x00000000]

"Finalizer" daemon prio=9 tid=0x009ccbb8 nid=0xb84 in Object.wait() [0x02b6f000..0x02b6fd68]

    at java.lang.Object.wait(Native Method)
    
    - waiting on <0x104fb160> (a java.lang.ref.ReferenceQueue$Lock)
    
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:111)
    
    - locked <0x104fb160> (a java.lang.ref.ReferenceQueue$Lock)
    
    at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:127)
    
    at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x009cb830 nid=0xf38 in Object.wait() [0x02b2f000..0x02b2fd68]

    at java.lang.Object.wait(Native Method)
    
    - waiting on <0x104fb1c8> (a java.lang.ref.Reference$Lock)
    
    at java.lang.Object.wait(Object.java:429)
    
    at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:115)
    
    - locked <0x104fb1c8> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00035b28 nid=0xe90 runnable [0x0007f000..0x0007fc38]

    at java.net.SocketInputStream.socketRead0(Native Method)
    
    at java.net.SocketInputStream.read(SocketInputStream.java:129)
    
    at java.net.SocketInputStream.read(SocketInputStream.java:182)
    
    at com.jcraft.jsch.ProxyHTTP.connect(Unknown Source)
    
    at org.apache.maven.wagon.providers.ssh.AbstractSshWagon.openConnection(AbstractSshWagon.java:181)
    
    at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
    
    at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:149)
    
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
    
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
    
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
    
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
    
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
    
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    
    at java.lang.reflect.Method.invoke(Method.java:324)
    
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 1.0-beta-2

**Issue Links:**
- [WAGON-172](https://issues.apache.org/jira/browse/WAGON-172) Add proxy support to SSH connections

3 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Stephen Coy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sfcoy)** commented

Here is the proxy config from settings.xml:

    <proxy>
      <id>optus</id>
      <active>false</active>
      <username>steve.coy</username>
      <password>XXXXXXX</password>
      <protocol>http</protocol>
      <host>proxy.optus.com.au</host>
      <port>8080</port>
      <nonProxyHosts>*.optus.com.au</nonProxyHosts>
    </proxy>

and here is the \<site> element from distributionManagement section of the pom.xml:

    <site>
      <id>inhouse</id>
      <name>Maven Project Web Server</name>
      <url>scp://webdevappl005.optus.com.au/var/webdev/master/${project.version}</url>
    </site>

**Comment by jira-importer** [comment]
**[Thierry Bressure](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tbressure)** commented

I got a similar error. I can't scp to deploy artifact with maven 2.0.8. All work fine with maven 2.0.4
After some investigation i find that maven 2.0.4 used jcraft 0.1.23 which simply ignore the response code of the proxy.
But maven 2.0.8 use jcraft 0.1.37 which test the response code of the proxy.

Since the class proxy used by wagon is proxyHTTP so in both case we should have an error. wagon should test if the proxy in settings.xml is enable and the protocol which the proxy is designed.

Here are technical information:

com.jcraft.jsch.ProcyHTTP.connect(122)   version 0.1.37

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

active is irrelevant due to a bug: see http://jira.codehaus.org/browse/MNG-2387

I'm unable to reproduce this as I just get a connection failure from the given HTTP proxy - but I suspect the above bug is the problem. You expect it to actually be disabled and it's not. Unscheduling for now.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

closing now as cannot reproduce - there have been some recent changes that should improve the proxying in this regard
