### ISSUE TITLE
[WAGON-145] Null pointer at org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:130)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#266]
**[Rahul Khot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkhot)** opened **[WAGON-145](https://issues.apache.org/jira/browse/WAGON-145?redirect=false)** and commented

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-deploy-plugin:2.3:deploy' -->
[DEBUG]   (f) artifact = abc-plugins:abc-plugin:maven-plugin:1.0.0.0
[DEBUG]   (f) attachedArtifacts = []
[DEBUG]   (f) deploymentRepository = [helixasptest] -> ftp://abc.com/public_html
[DEBUG]   (s) localRepository = [local] -> file://C:\Documents and Settings\user\.m2\repository
[DEBUG]   (f) packaging = maven-plugin
[DEBUG]   (f) pomFile = C:\Documents and Settings\user\workspace\abc\abc-plugins\abc-plugin\pom.xml
[DEBUG]   (f) updateReleaseInfo = false
[DEBUG]   - end configuration --
[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.NullPointerException

---

**Affects:** 1.0-alpha-6

**Comment by jira-importer** [comment]
**[Rahul Khot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkhot)** commented

Sorry accidently hit save:

I am getting a null pointer exception here is the stack:

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-deploy-plugin:2.3:deploy' -->
[DEBUG]   (f) artifact = abc-plugins:abc-plugin:maven-plugin:1.0.0.0
[DEBUG]   (f) attachedArtifacts = []
[DEBUG]   (f) deploymentRepository = [helixasptest] -> ftp://abc.com/public_html
[DEBUG]   (s) localRepository = [local] -> file://C:\Documents and Settings\user\.m2\repository
[DEBUG]   (f) packaging = maven-plugin
[DEBUG]   (f) pomFile = C:\Documents and Settings\user\workspace\abc\abc-plugins\abc-plugin\pom.xml
[DEBUG]   (f) updateReleaseInfo = false
[DEBUG]   - end configuration --
[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:127)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:235)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:153)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11 seconds
[INFO] Finished at: Wed Apr 11 19:57:28 PDT 2007
[INFO] Final Memory: 8M/15M
[INFO] ------------------------------------------------------------------------
Here is the relevant section in my POM:

\<distributionManagement>
\<repository>
\<id>abc\</id>
\<url>ftp://abc.com/public_html\</url>
\<layout>legacy\</layout>
\</repository>
\</distributionManagement>
\<build>
\<extensions>
\<extension>
\<groupId>org.apache.maven.wagon\</groupId>
\<artifactId>wagon-ftp\</artifactId>
\<version>1.0-beta-2\</version>
\</extension>
\</extensions>
\</build>

I have also added an entry in setting.xml file which defines the user name and password for the server Id abc. I have no other open connections to this ftp server from the machine I am running maven deploy goal.

Please let me know if you need any more information

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

have you tried with the latest releases ? 1.0-beta-2

**Comment by jira-importer** [comment]
**[Rahul Khot](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rkhot)** commented

Same stack as before Null Pointer at a different line

org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:130)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:235)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:153)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

for what i see either username or password in your settings is not defined, or the server id doesn't match

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed by throwing AuthenticationException if user/passwd are not defined

**Comment by jira-importer** [comment]
**[Alan Mehio](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alanmehio)** commented

I totally agree with Carlos Sanchez, if the server id does not match or if there is a username or password error, the method shoud through   AuthenticationException.

Regards,
Alan Mehio
London, UK
