### ISSUE TITLE
[WAGON-254] wagon-ftp :: error uploading site:: too many open files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#269]
**[Richard Gomes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rgomes1997)** opened **[WAGON-254](https://issues.apache.org/jira/browse/WAGON-254?redirect=false)** and commented

A complete log file is attached. Below you can see the stack trace:

[INFO] Error uploading site

Embedded error: IOException caught while attempting to upload /home/rgomes/workspace/jquantlib/target/site/testapidocs/org/jquantlib/testsuite/math/distributions/InverseCumulativeNormalTest.dot
Too many open files
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error uploading site
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:701)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:538)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:369)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:203)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:676)
... 16 more
Caused by: org.apache.maven.wagon.TransferFailedException: IOException caught while attempting to upload /home/rgomes/workspace/jquantlib/target/site/testapidocs/org/jquantlib/testsuite/math/distributions/InverseCumulativeNormalTest.dot
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:639)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:580)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:573)
at org.apache.maven.wagon.providers.ftp.FtpWagon.putDirectory(FtpWagon.java:500)
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:187)
... 18 more
Caused by: java.net.SocketException: Too many open files
at java.net.Socket.createImpl(Socket.java:388)
at java.net.Socket.\<init>(Socket.java:362)
at java.net.Socket.\<init>(Socket.java:180)
at org.apache.commons.net.DefaultSocketFactory.createSocket(DefaultSocketFactory.java:53)
at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:513)
at org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:388)
at org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:1388)
at org.apache.maven.wagon.providers.ftp.FtpWagon.ftpRecursivePut(FtpWagon.java:603)
... 27 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22 minutes 26 seconds
[INFO] Finished at: Wed Dec 31 10:49:27 GMT 2008
[INFO] Final Memory: 132M/370M
[INFO] --------------------------------------------------------------------

---

**Affects:** 1.0-beta-4

**Attachments:**
- [wagon-ftp_too-many-open-files.tar.bz2](https://issues.apache.org/jira/secure/attachment/12720811/wagon-ftp_too-many-open-files.tar.bz2) (_16.29 kB_)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

what is the netstat -a log? what is the maximum open socket allowed on your system?

**Comment by jira-importer** [comment]
**[Richard Gomes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rgomes1997)** commented

Hi,

I'm following directions on this article: https://support.bea.com/application_content/product_portlets/support_patterns/wls/TooManyOpenFilesPattern.html

$ cat /etc/security/limits.conf

1. /etc/security/limits.conf

# 

#Each line describes a limit for a user in the form:

# 

#\<domain>        \<type>  \<item>  \<value>

# 

#Where:
#\<domain> can be:
1.

    - an user name

2. 

       - a group name, with @group syntax

3. 

       - the wildcard *, for default entry

4. 

       - the wildcard %, can be also used with %group syntax,

5. 

       for maxlogin limit

# 

#\<type> can have the two values:
1.

    - "soft" for enforcing the soft limits

2. 

       - "hard" for enforcing hard limits

# 

#\<item> can be one of the following:
1.

    - core - limits the core file size (KB)

2. 

       - data - max data size (KB)

3. 

       - fsize - maximum filesize (KB)

4. 

       - memlock - max locked-in-memory address space (KB)

5. 

       - nofile - max number of open files

6. 

       - rss - max resident set size (KB)

7. 

       - stack - max stack size (KB)

8. 

       - cpu - max CPU time (MIN)

9. 

       - nproc - max number of processes

10. 

        - as - address space limit

11. 

        - maxlogins - max number of logins for this user

12. 

        - maxsyslogins - max number of logins on the system

13. 

        - priority - the priority to run user process with

14. 

        - locks - max number of file locks the user can hold

15. 

        - sigpending - max number of pending signals

16. 

        - msgqueue - max memory used by POSIX message queues (bytes)

17. 

        - nice - max nice priority allowed to raise to

18. 

        - rtprio - max realtime priority

# 

#\<domain>      \<type>  \<item>         \<value>

# 

* 

      soft    core            0

* 

      hard    rss             10000

#`@student`        hard    nproc           20
#`@faculty`        soft    nproc           20
#`@faculty`        hard    nproc           50
#ftp             hard    nproc           0
#`@student`        -       maxlogins       4

1. End of file

$ cat /proc/sys/fs/file-max
371153

$ cat /proc/sys/fs/file-nr
1920    0       371153

$ cat /proc/sys/fs/inode-nr
225525  3991

$ # the command below counts how many files where generated by "mvn clean site-deploy"
$ find maven2/ -print | wc -l
6585

1. This is the user configuration in LDAP
   dn: uid=continuum,ou=People,dc=jquantlib,dc=org
   objectClass: account
   objectClass: posixAccount
   objectClass: PureFTPdUser
   objectClass: simpleSecurityObject
   objectClass: top
   cn: continuum
   gidNumber: 33
   homeDirectory: /srv/users/continuum
   uid: continuum
   uidNumber: 1003
   userPassword:: secret
   description: continuum
   FTPDownloadBandwidth: -1
   FTPDownloadRatio: -1
   FTPgid: 33
   FTPHomeDirectory: /srv/users/continuum
   FTPQuotaFiles: -1
   FTPQuotaMBytes: -1
   FTPStatus: enabled
   FTPuid: 1003
   FTPUploadBandwidth: -1
   FTPUploadRatio: -1
   gecos: continuum
   loginShell: /bin/bash

and finally, as you requested:

$ netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 *:kshell                **:**                     LISTEN
tcp        0      0 localhost:2208          **:**                     LISTEN
tcp        0      0 localhost:ldap          **:**                     LISTEN
tcp        0      0 localhost:8005          **:**                     LISTEN
tcp        0      0 localhost:47943         **:**                     LISTEN
tcp        0      0 *:8009                  **:**                     LISTEN
tcp        0      0 localhost:mysql         **:**                     LISTEN
tcp        0      0 localhost:11211         **:**                     LISTEN
tcp        0      0 *:kerberos-adm          **:**                     LISTEN
tcp        0      0 localhost:34861         **:**                     LISTEN
tcp        0      0 localhost:5038          **:**                     LISTEN
tcp        0      0 *:www                   **:**                     LISTEN
tcp        0      0 *:webcache              **:**                     LISTEN
tcp        0      0 *:ftp                   **:**                     LISTEN
tcp        0      0 *:ssh                   **:**                     LISTEN
tcp        0      0 *:ipp                   **:**                     LISTEN
tcp        0      0 www.jquantlib.:kerberos **:**                     LISTEN
tcp        0      0 localhost:kerberos      **:**                     LISTEN
tcp        0      0 *:omniorb               **:**                     LISTEN
tcp        0      0 localhost:postgresql    **:**                     LISTEN
tcp        0      0 localhost:smtp          **:**                     LISTEN
tcp        0      0 localhost:6010          **:**                     LISTEN
tcp        0      0 localhost:6011          **:**                     LISTEN
tcp        0      0 *:https                 **:**                     LISTEN
tcp        0      0 localhost:6012          **:**                     LISTEN
tcp        0      0 *:ldaps                 **:**                     LISTEN
tcp        0      0 localhost:35548         localhost:11211         TIME_WAIT
tcp        0      0 localhost:5038          localhost:49752         ESTABLISHED
tcp        0      0 localhost:49752         localhost:5038          ESTABLISHED
tcp        0      0 localhost:6010          localhost:38531         ESTABLISHED
tcp        0      0 localhost:38531         localhost:6010          ESTABLISHED
tcp        0    640 www.jquantlib.org:ssh   developer.jquantl:40815 ESTABLISHED
tcp        0      0 www.jquantlib.org:ssh   developer.jquantl:43801 ESTABLISHED
tcp        0      0 www.jquantlib.org:ssh   developer.jquantl:51500 ESTABLISHED
tcp        0      0 www.jquantlib.org:www   llf520184.crawl.y:48821 TIME_WAIT
tcp        0      0 www.jquantlib.org:ldaps developer.jquantl:53911 ESTABLISHED
udp        0      0 localhost:32768         localhost:32768         ESTABLISHED
udp        0      0 www.jquantlib.org:13972 **:**
udp        0      0 *:13973                 **:**
udp        0      0 www.jquantlib.org:15776 **:**
udp        0      0 *:15777                 **:**
udp        0      0 *:44345                 **:**
udp        0      0 www.jquantlib.org:sip   **:**
udp        0      0 www.jquantlib.o:kpasswd **:**
udp        0      0 localhost:kpasswd       **:**
udp        0      0 www.jquantlib.org:15700 **:**
udp        0      0 *:15701                 **:**
udp        0      0 www.jquantlib.:kerberos **:**
udp        0      0 localhost:kerberos      **:**
udp        0      0 *:iax                   **:**
udp        0      0 *:mdns                  **:**
udp        0      0 *:ipp                   **:**
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  13     [ ]         DGRAM                    3721493  /dev/log
unix  2      [ ACC ]     STREAM     LISTENING     8074     public/cleanup
unix  2      [ ACC ]     STREAM     LISTENING     8081     private/tlsmgr
unix  2      [ ACC ]     STREAM     LISTENING     8085     private/rewrite
unix  2      [ ACC ]     STREAM     LISTENING     8089     private/bounce
unix  2      [ ACC ]     STREAM     LISTENING     8093     private/defer
unix  2      [ ACC ]     STREAM     LISTENING     8097     private/trace
unix  2      [ ACC ]     STREAM     LISTENING     8101     private/verify
unix  2      [ ACC ]     STREAM     LISTENING     8105     public/flush
unix  2      [ ACC ]     STREAM     LISTENING     8109     private/proxymap
unix  2      [ ACC ]     STREAM     LISTENING     8113     private/smtp
unix  2      [ ACC ]     STREAM     LISTENING     8117     private/relay
unix  2      [ ACC ]     STREAM     LISTENING     8121     public/showq
unix  2      [ ACC ]     STREAM     LISTENING     8125     private/error
unix  2      [ ACC ]     STREAM     LISTENING     8129     private/discard
unix  2      [ ACC ]     STREAM     LISTENING     8133     private/local
unix  2      [ ACC ]     STREAM     LISTENING     8137     private/virtual
unix  2      [ ACC ]     STREAM     LISTENING     8141     private/lmtp
unix  2      [ ACC ]     STREAM     LISTENING     8145     private/anvil
unix  2      [ ACC ]     STREAM     LISTENING     8149     private/scache
unix  2      [ ACC ]     STREAM     LISTENING     8153     private/maildrop
unix  2      [ ACC ]     STREAM     LISTENING     8157     private/uucp
unix  2      [ ACC ]     STREAM     LISTENING     8161     private/ifmail
unix  2      [ ACC ]     STREAM     LISTENING     8165     private/bsmtp
unix  2      [ ACC ]     STREAM     LISTENING     8169     private/scalemail-backend
unix  2      [ ACC ]     STREAM     LISTENING     8173     private/mailman
unix  2      [ ACC ]     STREAM     LISTENING     6436     /var/run/postgresql/.s.PGSQL.5432
unix  2      [ ACC ]     STREAM     LISTENING     6547     /var/run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     5117511  /var/run/cups/cups.sock
unix  2      [ ACC ]     STREAM     LISTENING     6639     /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     4874259  /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     4981340  /var/run/dirmngr/socket
unix  2      [ ACC ]     STREAM     LISTENING     393809   /tmp/ksocket-rgomesiKMpra/www.jquantlib.org-5286-48dcebd6
unix  2      [ ACC ]     STREAM     LISTENING     19699    /var/run/asterisk/asterisk.ctl
unix  2      [ ]         DGRAM                    3626     @/org/kernel/udev/udevd
unix  2      [ ACC ]     STREAM     LISTENING     4568798  /var/run/slapd/ldapi
unix  2      [ ACC ]     STREAM     LISTENING     4665380  /var/run/nscd/socket
unix  2      [ ACC ]     STREAM     LISTENING     4183765  /var/run/mysqld/mysqld.sock
unix  2      [ ACC ]     STREAM     LISTENING     6655     @/var/run/hald/dbus-wNQ7am3dzo
unix  2      [ ACC ]     STREAM     LISTENING     4423429  /var/run/.kcm_socket
unix  2      [ ]         DGRAM                    6663     @/org/freedesktop/hal/udev_event
unix  2      [ ACC ]     STREAM     LISTENING     397955   /tmp/fail2ban.sock
unix  2      [ ACC ]     STREAM     LISTENING     4425406  /tmp/ksocket-root/www.jquantlib.org-4c91-4942b3f8
unix  2      [ ACC ]     STREAM     LISTENING     6654     @/var/run/hald/dbus-k4WJlZ24rq
unix  2      [ ]         DGRAM                    5141346
unix  2      [ ]         DGRAM                    5126129
unix  3      [ ]         STREAM     CONNECTED     5126100
unix  3      [ ]         STREAM     CONNECTED     5126099
unix  2      [ ]         DGRAM                    5120896
unix  3      [ ]         STREAM     CONNECTED     5120866
unix  3      [ ]         STREAM     CONNECTED     5120865
unix  2      [ ]         DGRAM                    5117549
unix  2      [ ]         STREAM     CONNECTED     5104791
unix  2      [ ]         DGRAM                    5093171
unix  3      [ ]         STREAM     CONNECTED     5093168
unix  3      [ ]         STREAM     CONNECTED     5093167
unix  3      [ ]         STREAM     CONNECTED     4874262  /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     4874261
unix  3      [ ]         STREAM     CONNECTED     4874256
unix  3      [ ]         STREAM     CONNECTED     4874255
unix  2      [ ]         DGRAM                    4874227
unix  2      [ ]         DGRAM                    4666450
unix  2      [ ]         DGRAM                    4568794
unix  2      [ ]         STREAM     CONNECTED     4555313
unix  2      [ ]         STREAM     CONNECTED     4425403  /tmp/ksocket-rgomesiKMpra/kdeinit_localhost_12
unix  2      [ ]         DGRAM                    4423438
unix  2      [ ]         DGRAM                    4183759
unix  3      [ ]         STREAM     CONNECTED     4075811  /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     4075810
unix  2      [ ]         DGRAM                    3723123
unix  2      [ ]         STREAM     CONNECTED     393806   /tmp/ksocket-rgomesiKMpra/kdeinit_localhost_10
unix  2      [ ]         DGRAM                    11208
unix  3      [ ]         STREAM     CONNECTED     8176
unix  3      [ ]         STREAM     CONNECTED     8175
unix  3      [ ]         STREAM     CONNECTED     8172
unix  3      [ ]         STREAM     CONNECTED     8171
unix  3      [ ]         STREAM     CONNECTED     8168
unix  3      [ ]         STREAM     CONNECTED     8167
unix  3      [ ]         STREAM     CONNECTED     8164
unix  3      [ ]         STREAM     CONNECTED     8163
unix  3      [ ]         STREAM     CONNECTED     8160
unix  3      [ ]         STREAM     CONNECTED     8159
unix  3      [ ]         STREAM     CONNECTED     8156
unix  3      [ ]         STREAM     CONNECTED     8155
unix  3      [ ]         STREAM     CONNECTED     8152
unix  3      [ ]         STREAM     CONNECTED     8151
unix  3      [ ]         STREAM     CONNECTED     8148
unix  3      [ ]         STREAM     CONNECTED     8147
unix  3      [ ]         STREAM     CONNECTED     8144
unix  3      [ ]         STREAM     CONNECTED     8143
unix  3      [ ]         STREAM     CONNECTED     8140
unix  3      [ ]         STREAM     CONNECTED     8139
unix  3      [ ]         STREAM     CONNECTED     8136
unix  3      [ ]         STREAM     CONNECTED     8135
unix  3      [ ]         STREAM     CONNECTED     8132
unix  3      [ ]         STREAM     CONNECTED     8131
unix  3      [ ]         STREAM     CONNECTED     8128
unix  3      [ ]         STREAM     CONNECTED     8127
unix  3      [ ]         STREAM     CONNECTED     8124
unix  3      [ ]         STREAM     CONNECTED     8123
unix  3      [ ]         STREAM     CONNECTED     8120
unix  3      [ ]         STREAM     CONNECTED     8119
unix  3      [ ]         STREAM     CONNECTED     8116
unix  3      [ ]         STREAM     CONNECTED     8115
unix  3      [ ]         STREAM     CONNECTED     8112
unix  3      [ ]         STREAM     CONNECTED     8111
unix  3      [ ]         STREAM     CONNECTED     8108
unix  3      [ ]         STREAM     CONNECTED     8107
unix  3      [ ]         STREAM     CONNECTED     8104
unix  3      [ ]         STREAM     CONNECTED     8103
unix  3      [ ]         STREAM     CONNECTED     8100
unix  3      [ ]         STREAM     CONNECTED     8099
unix  3      [ ]         STREAM     CONNECTED     8096
unix  3      [ ]         STREAM     CONNECTED     8095
unix  3      [ ]         STREAM     CONNECTED     8092
unix  3      [ ]         STREAM     CONNECTED     8091
unix  3      [ ]         STREAM     CONNECTED     8088
unix  3      [ ]         STREAM     CONNECTED     8087
unix  3      [ ]         STREAM     CONNECTED     8084
unix  3      [ ]         STREAM     CONNECTED     8083
unix  3      [ ]         STREAM     CONNECTED     8080
unix  3      [ ]         STREAM     CONNECTED     8079
unix  3      [ ]         STREAM     CONNECTED     8077
unix  3      [ ]         STREAM     CONNECTED     8076
unix  3      [ ]         STREAM     CONNECTED     8073
unix  3      [ ]         STREAM     CONNECTED     8072
unix  3      [ ]         STREAM     CONNECTED     8068
unix  3      [ ]         STREAM     CONNECTED     8067
unix  2      [ ]         DGRAM                    8060
unix  3      [ ]         STREAM     CONNECTED     7932
unix  3      [ ]         STREAM     CONNECTED     7931
unix  3      [ ]         STREAM     CONNECTED     7768     /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     7767
unix  2      [ ]         DGRAM                    7766
unix  3      [ ]         STREAM     CONNECTED     7758     /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     7757
unix  3      [ ]         STREAM     CONNECTED     7688     @/var/run/hald/dbus-k4WJlZ24rq
unix  3      [ ]         STREAM     CONNECTED     7687
unix  3      [ ]         STREAM     CONNECTED     7499     /var/run/acpid.socket
unix  3      [ ]         STREAM     CONNECTED     7498
unix  3      [ ]         STREAM     CONNECTED     7493     @/var/run/hald/dbus-k4WJlZ24rq
unix  3      [ ]         STREAM     CONNECTED     7467
unix  3      [ ]         STREAM     CONNECTED     6658     @/var/run/hald/dbus-wNQ7am3dzo
unix  3      [ ]         STREAM     CONNECTED     6657
unix  3      [ ]         STREAM     CONNECTED     6642
unix  3      [ ]         STREAM     CONNECTED     6641
unix  2      [ ]         DGRAM                    6304
unix  2      [ ]         DGRAM                    6261

Thanks! :)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

do you have netstat output while site deploy is going on?

also

from your stacktrace, i found this

    if ( ftp.storeFile( fileName, new FileInputStream(

sourceFile ) ) )

it could be your system runs our of file descriptors since the
FileInputStream is not explicitly closed until GC.  you can help by
building your own version of wagon-ftp-beta-4 with this fix and
verify it

**Comment by jira-importer** [comment]
**[Richard Gomes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rgomes1997)** commented

Hi

Thanks for your quick answer.

No. I dont have a "netstat -a" whilst it is trying to deploy.
I was able to "deploy by hand" via konqueror (KDE) by copying to the desired URL ftp://  ... it takes a lot of time, because our javadocs contain UML diagrams and mathematical formulas, but it works fine. I've tried wagon-ssh and it works fine too. So, I'm already able to deploy. :)
You can have a look at deployed site at http://www.jquantlib.org/maven2/sites/jquantlib/

Unfortunately I cannot spend time trying to build wagon-ftp, as our project is huge and consumes a lot of my time :/ ... but I can try another version of wagon-ftp if you tell me which one I should try and from which repository.

Cheers :)

Richard Gomes
http://www.jquantlib.org/index.php/User:RichardGomes

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

I added the fix to explicitly close the stream

Revision: 730480
Author: dantran
Date: 1:05:59 PM, Wednesday, December 31, 2008
Message:
WAGON-254:Close FileInputStream explicitly

---

Modified : /maven/wagon/trunk/wagon-providers/wagon-ftp/src/main/java/org/apache/maven/wagon/providers/ftp/FtpWagon.java

you can build wagon's trunk and drop the wagon-ftp to your maven's footprint

**Comment by jira-importer** [comment]
**[Richard Gomes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rgomes1997)** commented

Hi Dan,

It works fine!

completed = /home/rgomes/workspace/jquantlib/target/site
ftp://ftp.jquantlib.org/maven2/sites/jquantlib/ - Session: Disconnecting
ftp://ftp.jquantlib.org/maven2/sites/jquantlib/ - Session: Disconnected
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20 minutes 46 seconds
[INFO] Finished at: Thu Jan 01 03:43:40 GMT 2009
[INFO] Final Memory: 134M/350M
[INFO] ------------------------------------------------------------------------

Thanks a lot!

Cheers :)

Richard Gomes
http://www.jquantlib.org/index.php/User:RichardGomes

**Comment by jira-importer** [comment]
**[Richard Gomes](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rgomes1997)** commented

==== For whomever interested ====

When running from command line:

---

I've circumvented the problem by defining 2 roles: developers and managers.
Developers execute "mvn clean integration-test" whilst managers execute "mvn -Drole=manager clean site-deploy", I mean: only managers are intended to deploy artifacts and/or generate the documentation website.

When profile "manager" is selected...

    * Maven 2.1.0-M1 is required instead of Maven 2.0.9
    * Newer versions of extensions are loaded, requiring Maven 2.1.0-M1
    * .m2/settings.xml must define username/password for deployment

When running inside Eclipse:

---

For some reason, external installation of Maven-2.0.9 was still giving problems. I really dont understand why
I reverted to Embeded installation and now it does not complain anymore.

See also:
https://jquant.svn.sourceforge.net/svnroot/jquant/trunk/jquantlib/pom.xml (SVN revision 641)
http://jira.codehaus.org/browse/MNGECLIP[SE-684](https://issues.apache.org/jira/browse/SE-684)

Cheers

Richard Gomes
