### ISSUE TITLE
[WAGON-85] deploy:deploy-file via wagon-webdav delete pom file referenced by -DpomFile

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#279]
**[Daniele](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ildella)** opened **[WAGON-85](https://issues.apache.org/jira/browse/WAGON-85?redirect=false)** and commented

I try to upload to a remote repository a 3rd party jar for which I have written a custom pom. I use this command:

mvn deploy:deploy-file -Dfile=toolkit-0.24.jar -DpomFile=toolkit-0.24.pom -DrepositoryId=sourcesense -Durl=dav:https://dev.sourcesense.com/repos/dev/maven2 -e

The jar is uploaded correctly and metadata xml files created as they should. But the pom of the project (toolkit-0.24-pom) is not uploaded becouse maven cannot find it! Indeed, pom is deleted from my disk during maven goal executions.

I have followed this instructions: http://docs.codehaus.org/display/MAVENUSER/Deploying+3rd+Party+Jars+With+WebDAV
so I have my pom.xml that points to wagon-webdav and the toolkit-0.24 pom, which I have written, is a simple pom with one dependency that works on my local repo

Take a look at the log, I am wondering of what
[INFO] Retrieving previous metadata from sourcesense
means. I attach the toolkit-0.24.pom

+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'deploy'.
  WAGON_VERSION: 1.0-beta-2
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Webdav Deployment POM
  [INFO]    task-segment: [deploy:deploy-file] (aggregator-style)
  [INFO] ----------------------------------------------------------------------------
  [INFO] [deploy:deploy-file]
  Uploading: https://dev.sourcesense.com/repos/dev/maven2/com/diasparsoftware/toolkit/0.24/toolkit-0.24.jar
  [INFO] Retrieving previous metadata from sourcesense
  [INFO] Uploading repository metadata for: 'artifact com.diasparsoftware:toolkit'
  [INFO] Retrieving previous metadata from sourcesense
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error installing artifact's metadata: Error installing metadata: Error copying POM to the local repository.

File /home/della/.m2/repository/com/diasparsoftware/toolkit/0.24/toolkit-0.24.pom does not exist
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error installing artifact's metadata: Error installing metadata: Error copying POM to the local repository.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:564)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:493)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:463)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:224)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error installing artifact's metadata: Error installing metadata: Error copying POM to the local repository.
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:240)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error installing artifact's metadata: Error installing metadata: Error copying POM to the local repository.
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:102)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:236)
... 18 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataDeploymentException: Error installing metadata: Error copying POM to the local repository.
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:432)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:86)
... 19 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataStoreException: Error copying POM to the local repository.
at org.apache.maven.project.artifact.ProjectArtifactMetadata.storeInLocalRepository(ProjectArtifactMetadata.java:96)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:428)
... 20 more
Caused by: java.io.IOException: File /home/della/.m2/repository/com/diasparsoftware/toolkit/0.24/toolkit-0.24.pom does not exist
at hidden.org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:845)
at org.apache.maven.project.artifact.ProjectArtifactMetadata.storeInLocalRepository(ProjectArtifactMetadata.java:92)
... 21 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Thu May 24 12:24:45 CEST 2007
[INFO] Final Memory: 3M/6M
[INFO] --------------------------------------------------------------------

---

**Affects:** 1.0-beta-2

**Attachments:**
- [toolkit-0.24.pom](https://issues.apache.org/jira/secure/attachment/12720825/toolkit-0.24.pom) (_621 bytes_)

**Comment by jira-importer** [comment]
**[Daniele](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ildella)** commented

Same problems occurs with other libraries I have in local with a custom pom.
.

**Comment by jira-importer** [comment]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** commented

Do not use deploy:deploy-file to deploy content from the local repository.

The deploy:deploy-file process utilizes the local repository.
It installs the contents to your local repository first, then performs a deploy from that location to the destination you specified.

The install process that deploy:deploy-file uses will attempt to copy your file to itself.
That doesn't work.

Use as the source directory **ANY** directory **BUT** the local repository.
