### ISSUE TITLE
[WAGON-84] exception deploying with webdav

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#280]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[WAGON-84](https://issues.apache.org/jira/browse/WAGON-84?redirect=false)** and commented

1.0-beta-2 was working reasonably well but when I try the 1.0-RC1, it seems there is a regression:

Uploading: http://sv1.tus.stchome.com/maven-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/adf-faces-1.0.pom
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Destination path exists and is not a WebDAV collection (directory): http://sv1.tus.stchome.com/mave
n-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: Destination path exists and is not a WebDAV collec
tion (directory): http://sv1.tus.stchome.com/maven-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:564)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: Destination path exists and is not a WebDAV col
lection (directory): http://sv1.tus.stchome.com/maven-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:174)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: Destination path exists and is
not a WebDAV collection (directory): http://sv1.tus.stchome.com/maven-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:94)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:152)
... 18 more
Caused by: org.apache.maven.wagon.TransferFailedException: Destination path exists and is not a WebDAV collection (directory): http:
//sv1.tus.stchome.com/maven-repos/stc/com/stchome/adf/view/faces/adf-faces/1.0/
at org.apache.maven.wagon.providers.webdav.WebDavWagon.mkdirs(WebDavWagon.java:333)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.put(WebDavWagon.java:236)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:237)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:153)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)
... 19 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Thu May 10 16:12:27 EDT 2007
[INFO] Final Memory: 9M/17M
[INFO] --------------------------------------------------------------------

---

**Affects:** 1.0-beta-3

**Issue Links:**
- [WAGON-96](https://issues.apache.org/jira/browse/WAGON-96) WebDAV deploy fails with - Failed to create destination WebDAV collection
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I've seen this too - I think it might be a result of the mkdirs() call which is not identifying the directory as a collection

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this was resolved by the switch to jackrabbit

**Comment by jira-importer** [comment]
**[Hendy Irawan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ceefour)** commented

wagon-webdav is now (name changed) wagon-webdav-jackrabbit

I'm using 1.0-beta-5 and no longer having this problem

I experienced this problem, along with WAGON-96 , when still using wagon-webdav 1.0-beta-2
