### ISSUE TITLE
[WAGON-130] FTP Deploy Error: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#305]
**[Alan Gross](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alan79)** opened **[WAGON-130](https://issues.apache.org/jira/browse/WAGON-130?redirect=false)** and commented

FTP Connection/GET/PUT works fine with FTP Clients (Filezilla, Windows Commandline FTP Client).

When calling "mvn deploy" the following StringIndexOutOfBoundsException occurs (see down below).

Is this a known issue? FTP seems to me the easiest solution for distributionmgmt in a window environment. I was trying to deploy with SSH, but there it seems to be necessary to create a windows user account for each user deploying to the maven repository. Further it seems like User/Password Authentication is not working (only Certificates). Until now i didn't get it to work. With FTP it is possible to use one user account for all developers.

Any help is appreciated!!

Best regards
Alan

Trace (mvn deploy -e):

[INFO] Retrieving previous build number from alan-maven-repo-ftp
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] String index out of range: -27
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.StringIndexOutOfBoundsException: String index out of range: -27
at java.lang.String.substring(String.java:1768)
at org.apache.commons.net.ftp.FTPClient.__parsePassiveModeReply(FTPClien
t.java:341)
at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.j
ava:511)
at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.ja
va:2390)
at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.ja
va:2364)
at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2141)
at org.apache.maven.wagon.providers.ftp.FtpWagon.fillInputData(FtpWagon.
java:317)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(D
efaultWagonManager.java:462)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMeta
data(DefaultWagonManager.java:363)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetada
taManager.resolveAlways(DefaultRepositoryMetadataManager.java:364)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetada
taManager.resolveAlways(DefaultRepositoryMetadataManager.java:318)
at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLat
estSnapshotBuildNumber(SnapshotTransformation.java:161)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformF
orDeployment(SnapshotTransformation.java:100)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationMana
ger.transformForDeployment(DefaultArtifactTransformationManager.java:78)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(Def
aultArtifactDeployer.java:71)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162
)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] --------------------------------------------------------------------

---
No further details from [WAGON-130](https://issues.apache.org/jira/browse/WAGON-130?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I don't see any related fixes in commons-net - have you overcome the issue?
