### ISSUE TITLE
[WAGON-140] WAGONFTP Nullpointer Exception

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#309]
**[Jamish Patel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nap4110)** opened **[WAGON-140](https://issues.apache.org/jira/browse/WAGON-140?redirect=false)** and commented

Getting the following error similar to this user:
http://jira.codehaus.org/browse/WAGONFTP-17

Pretty sure user id and password is correct for the machine that I am trying to ftp to
One thing I did not understand in the url above was 'will be thrown if there is a host mismatch'  
Mismatch with what?

Here's the exception:

[INFO] Retrieving previous build number from internal-snapshot
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection(FtpWagon.java:127)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:354)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:295)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:356)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:310)
at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:158)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:97)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:61)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:68)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162)

---
No further details from [WAGON-140](https://issues.apache.org/jira/browse/WAGON-140?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this appears to be on the older 1.0-beta-1. It seems to work ok for me now.
