### ISSUE TITLE
[WAGON-135] Error deploying artifact: Unable to create directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#323]
**[troy ronning](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=troy.ronning)** opened **[WAGON-135](https://issues.apache.org/jira/browse/WAGON-135?redirect=false)** and commented

I'm trying to deploy a project and receiving error below.
.........
[INFO] [deploy:deploy]
altDeploymentRepository = test.ftp::default::ftp://\<server>
[INFO] Using alternate deployment repository test.ftp::default::ftp://\<server>
[INFO] Retrieving previous build number from test.ftp
[DEBUG] repository metadata for: 'snapshot org.test:foo:1.0-SNAPSHOT' could not be found on repository: test.ftp
Uploading: ftp://\<server>/org/test/foo/1.0-SNAPSHOT/foo-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Unable to create directory org

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: Unable to create directory org
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:564)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: Unable to create directory org
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:174)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: Unable to create directory org
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:94)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162)
... 18 more
Caused by: org.apache.maven.wagon.TransferFailedException: Unable to create directory org
at org.apache.maven.wagon.providers.ftp.FtpWagon.fillOutputData(FtpWagon.java:264)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:133)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:237)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:153)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)
... 19 more

I have wagon-ftp set as a build extension.

    <build>
        <extensions>
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-ftp</artifactId>
                <version>1.0-alpha-6</version>
            </extension>
        </extensions>
    </build> 

I can execute 'mkd' successfully from ftp CLI.

---
No further details from [WAGON-135](https://issues.apache.org/jira/browse/WAGON-135?redirect=false)

**Comment by jira-importer** [comment]
**[Baris Efe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gunebakan)** commented

Hi,
I was suffering with the same issue and I find the solution after some ftp server debug.
I am using proftpd and there was no

DefaultRoot                     ~

line on my
/etc/proftpd/proftpd.conf

So when you try to run
#mvn deploy

you can see "CWD /" command on the server side and if you do not have
DefaultRoot                     ~
it really goes to file system root and you get
[INFO] Error deploying artifact: Unable to create directory org
error that you do not get on normal ftp(Because you do not run #dir / command.).

Hope this help to you and others.
