### ISSUE TITLE
[WAGON-138] Fix errant exception thrown in closeConnection()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#325]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[WAGON-138](https://issues.apache.org/jira/browse/WAGON-138?redirect=false)** and commented

Fix errant exception thrown in closeConnection() of the ftp wagon which is caused by calling ftp.disconnect(). Nothing wrong seems to happen in the test. But this is what we get:

java.lang.NullPointerException
at java.io.BufferedInputStream.read(BufferedInputStream.java:205)
at java.io.FilterInputStream.read(FilterInputStream.java:66)
at java.io.PushbackInputStream.read(PushbackInputStream.java:120)
at org.apache.commons.net.io.FromNetASCIIInputStream.__read(FromNetASCIIInputStream.java:114)
at org.apache.commons.net.io.FromNetASCIIInputStream.read(FromNetASCIIInputStream.java:209)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:183)
at java.io.BufferedInputStream.read(BufferedInputStream.java:201)
at org.apache.commons.net.telnet.TelnetInputStream.__read(TelnetInputStream.java:140)
at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:464)
at java.lang.Thread.run(Thread.java:534)

But it seems to happen even if we don't shut down the streams so I'm not sure what's going on internally in commons-net.

---
No further details from [WAGON-138](https://issues.apache.org/jira/browse/WAGON-138?redirect=false)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

I think this is no longer applicable
