### ISSUE TITLE
[WAGON-302] ResourceDoesNotExistException when trying to deploy artifact via HTTP

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#364]
**[Elifarley Callado Coelho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elifarley@yahoo.com)** opened **[WAGON-302](https://issues.apache.org/jira/browse/WAGON-302?redirect=false)** and commented

Sometimes, when I try to deploy an artifact to my Artifactory 2.2.1 server via HTTP, I receive this type of error message:

Deploying the main artifact mplace-ear-2.2.3-SNAPSHOT.ear
[INFO ] Retrieving previous build number from artifactory
[INFO ] repository metadata for: 'snapshot net.webb.mplace:mplace-ear:2.2.3-SNAPSHOT' could not be found on repository: artifactory, so will be created
[INFO ] Retrieving previous metadata from artifactory
[INFO ] repository metadata for: 'snapshot net.webb.mplace:mplace-ear:2.2.3-SNAPSHOT' could not be found on repository: artifactory, so will be created
[INFO ] Uploading repository metadata for: 'snapshot net.webb.mplace:mplace-ear:2.2.3-SNAPSHOT'
[INFO ] Retrieving previous metadata from artifactory
[INFO ] Uploading repository metadata for: 'artifact net.webb.mplace:mplace-ear'
[INFO ] Uploading project information for mplace-ear 2.2.3-SNAPSHOT
ERROR: Error installing artifact's metadata: Error while deploying metadata: Resource to deploy not found: File: http://chronos:8080/artifactory/libs-snapshots-local/br/com/webb/mplace/mplace-ear/2.2.3-SNAPSHOT/mplace-ear-2.2.3-SNAPSHOT.pom does not exist
org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error installing artifact's metadata: Error while deploying metadata: Resource to deploy not found: File: http://chronos:8080/artifactory/libs-snapshots-local/br/com/webb/mplace/mplace-ear/2.2.3-SNAPSHOT/mplace-ear-2.2.3-SNAPSHOT.pom does not exist
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:102)
at hudson.maven.reporters.MavenArtifactRecord.deploy(MavenArtifactRecord.java:119)
at hudson.maven.reporters.MavenAggregatedArtifactRecord.deploy(MavenAggregatedArtifactRecord.java:79)
at hudson.maven.RedeployPublisher.perform(RedeployPublisher.java:108)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:582)
at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:563)
at hudson.maven.MavenModuleSetBuild$RunnerImpl.post2(MavenModuleSetBuild.java:594)
at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:528)
at hudson.model.Run.run(Run.java:1233)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:304)
at hudson.model.ResourceController.execute(ResourceController.java:88)
at hudson.model.Executor.run(Executor.java:122)
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataDeploymentException: Error while deploying metadata: Resource to deploy not found: File: http://chronos:8080/artifactory/libs-snapshots-local/br/com/webb/mplace/mplace-ear/2.2.3-SNAPSHOT/mplace-ear-2.2.3-SNAPSHOT.pom does not exist
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:450)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:86)
... 12 more
Caused by: org.apache.maven.wagon.TransferFailedException: Resource to deploy not found: File: http://chronos:8080/artifactory/libs-snapshots-local/br/com/webb/mplace/mplace-ear/2.2.3-SNAPSHOT/mplace-ear-2.2.3-SNAPSHOT.pom does not exist
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:283)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifactMetadata(DefaultWagonManager.java:169)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.deploy(DefaultRepositoryMetadataManager.java:446)
... 13 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: File: http://chronos:8080/artifactory/libs-snapshots-local/br/com/webb/mplace/mplace-ear/2.2.3-SNAPSHOT/mplace-ear-2.2.3-SNAPSHOT.pom does not exist
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.put(LightweightHttpWagon.java:168)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:244)
... 15 more

---
No further details from [WAGON-302](https://issues.apache.org/jira/browse/WAGON-302?redirect=false)

**Comment by jira-importer** [comment]
**[Elifarley Callado Coelho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elifarley@yahoo.com)** commented

This problem was caused by a bad UTF-8 character sequence in the POM. Fixing the POM solved the problem.
