### ISSUE TITLE
[WAGON-311] NPE and CommandExecutionException when creating directory over SSH

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#372]
**[David Pilato](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dpilato)** opened **[WAGON-311](https://issues.apache.org/jira/browse/WAGON-311?redirect=false)** and commented

When deploying site with mvn site:deploy on multi module project, I get really often (about 90%) the following error :
[INFO] ------------------------------------------------------------------------
[INFO] Building BANACO - Projet principal (POM)
[INFO]    task-segment: [site:deploy]
[INFO] ------------------------------------------------------------------------
[INFO] [site:deploy {execution: default-cli}]
scp://cdxlan025.douane:22/var/jboss/server/archiva/deploy/CID-PORTAIL-DEV.war/site/banaco/1.2.1-SNAPSHOT/ - Session: Opened  
Executing command: mkdir -p /var/jboss/server/archiva/deploy/CID-PORTAIL-DEV.war/site/banaco/1.2.1-SNAPSHOT/.
scp://cdxlan025.douane:22/var/jboss/server/archiva/deploy/CID-PORTAIL-DEV.war/site/banaco/1.2.1-SNAPSHOT/ - Session: Disconnecting  
scp://cdxlan025.douane:22/var/jboss/server/archiva/deploy/CID-PORTAIL-DEV.war/site/banaco/1.2.1-SNAPSHOT/ - Session: Disconnected
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error uploading site

Embedded error: Error performing commands for file transfer
java.lang.NullPointerException
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error uploading site
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:229)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error performing commands for file transfer
at org.apache.maven.wagon.providers.ssh.ScpHelper.putDirectory(ScpHelper.java:232)
at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.putDirectory(AbstractJschWagon.java:360)
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:215)
... 19 more
Caused by: org.apache.maven.wagon.CommandExecutionException: Cannot execute remote command: mkdir -p /var/jboss/server/archiva/deploy/CID-PORTAIL-DEV.war/site/banaco/1.2.1-SNAPSHOT/.
at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCommand(AbstractJschWagon.java:326)
at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCommand(AbstractJschWagon.java:379)
at org.apache.maven.wagon.providers.ssh.ScpHelper.putDirectory(ScpHelper.java:228)
... 21 more
Caused by: com.jcraft.jsch.JSchException: java.lang.NullPointerException
at com.jcraft.jsch.Channel.connect(Channel.java:205)
at com.jcraft.jsch.Channel.connect(Channel.java:144)
at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCommand(AbstractJschWagon.java:305)
... 23 more

It can happen on the main module (pom) or on other module (jar, war, ...).

So automatic SNAPSHOT publishing with Hudson can not work as I would like...

Thanks for any help.

---

**Affects:** 1.0-beta-6

5 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Michiel Meeuwissen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihxil)** commented

I'm experiencing the same problem. I'm not using mvn site:deploy, but simply mvn deploy. So I think the site plugin may not be related.

Also using Hudson.

**Comment by jira-importer** [comment]
**[Nikolay Kushin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kushin)** commented

I experienced the same problem

```
 
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error handling resource

Embedded error: Cannot execute remote command: mkdir -p /test/application/views/
engine/compile
java.lang.NullPointerException
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error handling resource
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:719)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6
0)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error handling resour
ce
        at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingl
eWagonMojo.java:67)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:490)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:694)
        ... 17 more
Caused by: org.apache.maven.wagon.TransferFailedException: Cannot execute remote
 command: mkdir -p /test/application/views/engine/compile
        at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.fillOutputData(Scp
Wagon.java:329)
        at org.apache.maven.wagon.StreamWagon.getOutputStream(StreamWagon.java:1
88)
        at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:159)
        at org.codehaus.mojo.wagon.shared.DefaultWagonUpload.upload(DefaultWagon
Upload.java:71)
        at org.codehaus.mojo.wagon.shared.DefaultWagonUpload.upload(DefaultWagon
Upload.java:81)
        at org.codehaus.mojo.wagon.UploadMojo.execute(UploadMojo.java:114)
        at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingl
eWagonMojo.java:63)
        ... 19 more
Caused by: org.apache.maven.wagon.CommandExecutionException: Cannot execute remo
te command: mkdir -p /test/application/views/engine/compile
        at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCo
mmand(AbstractJschWagon.java:326)
        at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCo
mmand(AbstractJschWagon.java:379)
        at org.apache.maven.wagon.providers.ssh.ScpHelper.createRemoteDirectorie
s(ScpHelper.java:344)
        at org.apache.maven.wagon.providers.ssh.jsch.ScpWagon.fillOutputData(Scp
Wagon.java:323)
        ... 25 more
Caused by: com.jcraft.jsch.JSchException: java.lang.NullPointerException
        at com.jcraft.jsch.Channel.connect(Channel.java:205)
        at com.jcraft.jsch.Channel.connect(Channel.java:144)
        at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.executeCo
mmand(AbstractJschWagon.java:305)
        ... 28 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 18 seconds
[INFO] Finished at: Tue Oct 26 10:09:06 MSD 2010
[INFO] Final Memory: 11M/29M
[INFO] ------------------------------------------------------------------------
```

```
 
...
  <build>

    <extensions>
      <extension>
        <groupId>org.apache.maven.wagon</groupId>
        <artifactId>wagon-ssh</artifactId>
        <version>1.0-beta-6</version>
      </extension>
    </extensions>



    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>wagon-maven-plugin</artifactId>
        <version>1.0-beta-3</version>
        <configuration>
          <url>${url.base}</url>
          <serverId>${serverId}</serverId>
          <skip>false</skip>
        </configuration>

        <executions>

          <execution>
            <id>upload-app-files</id>
            <phase>install</phase>
            <goals>
              <goal>upload</goal>
            </goals>
            <configuration>
              <fromDir>${basedir}</fromDir>
              <includes>application/**/*</includes>
              <toDir>test</toDir>
            </configuration>
          </execution>

        </executions>
      </plugin>
    </plugins>

 
  </build>
...
```

Apache Maven 2.2.1 (r801777; 2009-08-06 23:16:01+0400)
Java version: 1.6.0_21
Java home: C:\Program Files\Java\jre6
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"
