### ISSUE TITLE
[WAGON-319] Site deployment fails on googlecode repository (unnecessary '/./' path element in WebDAV URL)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#379]
**[Marcin Kuthan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkuthan)** opened **[WAGON-319](https://issues.apache.org/jira/browse/WAGON-319?redirect=false)** and commented

Hi,

I configured my project to use Wagon WebDAV provider to deploy project
site. In general it works as I expected but it fails if the site is
deployed on googlecode.

Transfer error: org.apache.maven.wagon.TransferFailedException: Failed
to transfer file:
https://m4enterprise.googlecode.com/svn/site/./css/maven-base.css.
Return code is: 500
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-site-plugin:3.0-beta-3:deploy
(default-deploy) on project corporate-pom: Error uploading site:
Failed to transfer file:
https://m4enterprise.googlecode.com/svn/site/./css/maven-base.css.
Return code is: 500 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to
execute goal org.apache.maven.plugins:maven-site-plugin:3.0-beta-3:deploy
(default-deploy) on project corporate-pom: Error uploading site
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:203)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:140)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:451)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:188)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:134)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:271)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:195)
... 19 more
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to
transfer file: https://m4enterprise.googlecode.com/svn/site/./css/maven-base.css.
Return code is: 500
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:368)
at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:280)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.putDirectory(WebDavWagon.java:188)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.putDirectory(WebDavWagon.java:182)
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:257)
... 21 more

I filled an issue in googlecode bug tracker
(http://code.google.com/p/support/issues/detail?id=4786). There is a
suspicion that '/./' part of URL is an error cause.

It has been discussed also on Maven mailing list:
http://maven.40175.n5.nabble.com/How-to-avoid-part-of-URL-during-site-deployment-td3307034.html

Because I don't know exactly which Maven plugin is responsible for URL pre-processing during site deployment, the similar issue was created for site plugin:
http://jira.codehaus.org/browse/MSITE-531

Thanks,
Marcin

---

**Attachments:**
- [patch-MSITE-531.diff](https://issues.apache.org/jira/secure/attachment/12720792/patch-MSITE-531.diff) (_5.94 kB_)
- [patch-MSITE-531-corrected-style.diff](https://issues.apache.org/jira/secure/attachment/12720834/patch-MSITE-531-corrected-style.diff) (_5.94 kB_)

**Issue Links:**
- [MSITE-601](https://issues.apache.org/jira/browse/MSITE-601) Period added to URL prevents proper cloning with Mercurial

- [MSITE-531](https://issues.apache.org/jira/browse/MSITE-531) Site deployment fails on googlecode repository (unnecessary '/./' path element in WebDAV URL)
 (_**"supercedes"**_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Andrew Phillips](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=demobox)** commented

See also https://github.com/demobox/wagon-webdav-jackrabbit/

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

some fix has been added regarding to not add extra / can you try with 2.0-SNAPSHOT
Thanks

**Comment by jira-importer** [comment]
**[Andrew Phillips](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=demobox)** commented

`@Olivier`: Thanks! I hope Marcin can test - we're no longer using Google Code (i.e. the WebDAV wagon) for our use case :-(

**Comment by jira-importer** [comment]
**[Marcin Kuthan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkuthan)** commented

I'm also not using google code for site deployment anymore. WebDAV upload == one commit into the repository per file :-( - the best method to see "high activity" on the project status ;-)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
