### ISSUE TITLE
[WAGON-338] Exception from cyberneko from jenkins repo listing

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#395]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[WAGON-338](https://issues.apache.org/jira/browse/WAGON-338?redirect=false)** and commented

Trying to use the wagon-maven-plugin to copy from a current jenkins https repo:

[INFO] Error during performing repository copy

Embedded error: -1
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during performing repository copy
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during performing repository copy
at org.codehaus.mojo.wagon.AbstractCopyMojo.execute(AbstractCopyMojo.java:53)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
at hidden.org.cyberneko.html.HTMLTagBalancer$InfoStack.pop(HTMLTagBalancer.java:1262)
at hidden.org.cyberneko.html.HTMLTagBalancer.startElement(HTMLTagBalancer.java:669)
at hidden.org.cyberneko.html.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2489)
at hidden.org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:1950)
at hidden.org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:872)
at hidden.org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:496)
at hidden.org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:449)
at org.apache.maven.wagon.shared.http.HtmlFileListParser.parseFileList(HtmlFileListParser.java:71)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.getFileList(LightweightHttpWagon.java:343)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:283)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scan(WagonDirectoryScanner.java:245)
at org.codehaus.mojo.wagon.shared.DefaultWagonDownload.getFileList(DefaultWagonDownload.java:51)
at org.codehaus.mojo.wagon.shared.DefaultWagonDownload.download(DefaultWagonDownload.java:59)
at org.codehaus.mojo.wagon.shared.DefaultWagonCopy.copy(DefaultWagonCopy.java:67)
at org.codehaus.mojo.wagon.CopyMojo.copy(CopyMojo.java:77)
at org.codehaus.mojo.wagon.AbstractCopyMojo.execute(AbstractCopyMojo.java:49)
... 19 more

---

**Affects:** 1.0-beta-2, 1.0-beta-7, 2.0

**Backported to:** [1.0](https://github.com/apache/maven-wagon/milestone/16?closed=1)

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

r1143141 | bimargulies | 2011-07-05 12:56:17 -0400 (Tue, 05 Jul 2011) | 8 lines

[WAGON-338] Exception from cyberneko from jenkins repo listing

the html listing parser was coded to use Cyberneko. This orphaned ball of complexity crashes on some things
it does not understand, including some output from the Jenkins CI system when it is serving as a repository.

A maintained, superior alternative is Jsoup. This change switches wagon-http-shared4 to use it.
It passes all the tests.

---

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

Hi Benson!

Go on with the upgrade. jsoup is MIT, so this should be fine also.
Please note that we need to fix this in both wagon-http-shared4 and wagon-http-shared. Both contain the identical HtmlFileListParser. Those two libs only differ in the httpclient implementation, but we sadly cannot get rid of the httpclient-3 based wagon-http-shared yet since jackrabbit (used in the webdav wagon) is still using it internally and is externalizing those classes :/

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

---

r1143148 | bimargulies | 2011-07-05 13:26:11 -0400 (Tue, 05 Jul 2011) | 4 lines

[WAGON-338] Exception from cyberneko from jenkins repo listing

backport of change from trunk.

---
