### ISSUE TITLE
[WAGON-339] Run out of heap looking at contents of a Jenkins repo

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#400]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** opened **[WAGON-339](https://issues.apache.org/jira/browse/WAGON-339?redirect=false)** and commented

Reading from https://builds.apache.org/job/Lucene-Solr-Maven-trunk/lastSuccessfulBuild/artifact/maven_artifacts,
there's an out of memory. Looks a bit like an infinte recursion, don't it?

[INFO] Trace
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOfRange(Arrays.java:3209)
at java.lang.String.\<init>(String.java:215)
at java.lang.StringBuffer.toString(StringBuffer.java:585)
at sun.net.www.ParseUtil.toString(ParseUtil.java:315)
at sun.net.www.ParseUtil.createURI(ParseUtil.java:289)
at sun.net.www.ParseUtil.toURI(ParseUtil.java:266)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:905)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:158)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1172)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:379)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:318)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:129)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.getFileList(LightweightHttpWagon.java:328)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:283)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)
at org.codehaus.mojo.wagon.shared.WagonDirectoryScanner.scandir(WagonDirectoryScanner.java:322)

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

oops, this is probably a problem with the mojo.
