### ISSUE TITLE
[WAGON-353] StreamWagon.putFromStream() fails with IllegalStateException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#405]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[WAGON-353](https://issues.apache.org/jira/browse/WAGON-353?redirect=false)** and commented

The following exception arises when aether:1.12+ and wagon-http:2.0 meet:

```
java.lang.IllegalStateException: Should not be using the streaming wagon for HTTP PUT
	at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillOutputData(AbstractHttpClientWagon.java:930)
	at org.apache.maven.wagon.StreamWagon.getOutputStream(StreamWagon.java:188)
	at org.apache.maven.wagon.StreamWagon.putFromStream(StreamWagon.java:272)
	at org.apache.maven.wagon.StreamWagon.putFromStream(StreamWagon.java:252)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.uploadChecksum(WagonRepositoryConnector.java:885)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.uploadChecksums(WagonRepositoryConnector.java:861)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:818)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:475)
```

Despite wagon-http:2.0 implementing `StreamingWagon` it fails to provide the declared functionality. The missing functionality should either be added/restored or the interface revised to allow clients to detect whether streaming PUTs are supported or not.

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

fixed.
I leave the issue until benjamin tests.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Looks good now, thanks.
