### ISSUE TITLE
[WAGON-354] Site deployment always fails with StringIndexOutOfBoundsException in SftpWagon

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#410]
**[Juergen Kellerer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juergenk)** opened **[WAGON-354](https://issues.apache.org/jira/browse/WAGON-354?redirect=false)** and commented

I always get StringIndexOutOfBoundsException on the attempt to deploy a site with SFTP using Maven 3 + Site Plugin 3.

Calling **"mvn site-deploy"** causes:

```
...
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
        at org.apache.maven.plugins.site.AbstractDeployMojo.push(AbstractDeployMojo.java:464)
        at org.apache.maven.plugins.site.AbstractDeployMojo.deploy(AbstractDeployMojo.java:296)
        at org.apache.maven.plugins.site.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:257)
        at org.apache.maven.plugins.site.AbstractDeployMojo.execute(AbstractDeployMojo.java:165)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error occurred while deploying 'c:\Projects\OS\doxia-include\target\site' to remo
te repository: sftp://web.sourceforge.net/home/groups/d/do/doxia-include/htdocs/:
        at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.putDirectory(SftpWagon.java:286)
        at org.apache.maven.plugins.site.AbstractDeployMojo.push(AbstractDeployMojo.java:447)
        ... 24 more
Caused by: 4:
        at com.jcraft.jsch.ChannelSftp.mkdir(ChannelSftp.java:1713)
        at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.mkdir(SftpWagon.java:204)
        at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.ftpRecursivePut(SftpWagon.java:300)
        at org.apache.maven.wagon.providers.ssh.jsch.SftpWagon.putDirectory(SftpWagon.java:277)
        ... 25 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:686)
        at com.jcraft.jsch.ChannelSftp.remoteAbsolutePath(ChannelSftp.java:2367)
        at com.jcraft.jsch.ChannelSftp.mkdir(ChannelSftp.java:1691)
        ... 28 more
```

**The configuration is**:

```xml
 
<properties>
  <application.id>doxia-include</application.id>
</properties>
<distributionManagement>
  <site>
    <id>${application.id}.shell.sourceforge.net</id>
    <name>${application.id}.shell.sourceforge.net</name>
    <url>sftp://web.sourceforge.net/home/groups/d/do/${application.id}/htdocs</url>
  </site>
```

(Btw. I tried variuous urls, "../htdocs", "../htdocs/" and "../htdocs/." but the site plugin always normalizes them to "../htdocs/", which is actually the right thing to do.)

**My assumption why it happens:**

I looked at the sources of wagon (particularly to the methods mentioned in the stack trace), and I think the issue seems to be that:
- Site Plugin 3 always normalizes the remote directory to end with a trailing slash.
- WagonSftp.putDirectory:277 calls ScpHelper.getResourceFilename( destinationDirectory ) on this directory which returns an empty string.
- WagonSfto.ftpRecursivePut:300 calls mkdir with an empty string which causes the exception.

Actually it looks as if older site plugins added a trailing "/." to the path instead of just "/" as otherwise it would have been broken before (I did not verify this). Nevertheless I think the bug is in the Wagon implementation as it should not fail if the destination is given like this.

---

**Affects:** 1.0, 2.0

**Attachments:**
- [0001-WAGON-354-Site-deployment-always-fails-with-StringIn.patch](https://issues.apache.org/jira/secure/attachment/12720749/0001-WAGON-354-Site-deployment-always-fails-with-StringIn.patch) (_5.14 kB_)

**Issue Links:**
- [WAGON-323](https://issues.apache.org/jira/browse/WAGON-323) -keyboard-interactive method is used even when password is supplied

- [MSITE-681](https://issues.apache.org/jira/browse/MSITE-681) Error uploading site - String index out of range: 0

5 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Nicolas Richeton](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nricheton)** commented

I face the same issue. This totally prevents site deployment

**Comment by jira-importer** [comment]
**[Archimedes Trajano](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trajano)** commented

Is there a workaround?

**Comment by jira-importer** [comment]
**[Jackie Noi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jackienoi)** commented

This problem starts as of version 2.3 of maven-site-plugin - also in Maven 2. A temporary workaround is to downgrade to 2.2.

**Comment by jira-importer** [comment]
**[Archimedes Trajano](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trajano)** commented

Is there a workaround for Maven 3?

**Comment by jira-importer** [comment]
**[Michael Koch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tensberg)** commented

I agree with Juergens analysis and conclusion that `SftpWagon.putDirectory` should not fail if the `destinationDirectory` ends with a `"/"`. I've attached a patch which changes `ScpHelper.getResourceFilename` to return a `"."` instead of `""` if the resource path ends with a `"/"`. This fixes the site deployment for me.

**Comment by jira-importer** [comment]
**[Nicolas Richeton](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nricheton)** commented

This is a critical issue opened for more than 20 months with no workaround for Maven3 (other than 'don't use sftp'). A patch has been available for 4 months. Is there any issue with the attached patch ? Is there anything we can do to help to get this committed and to have the patched wagon-ssh released ?

**Comment by jira-importer** [comment]
**[Drew MacInnis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=drewmacinnis@gmail.com)** commented

I was able to perform site-deploy via sftp for my project using these plugin settings:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-site-plugin</artifactId>
    <version>3.3</version>
    <configuration>
        <chmod>false</chmod>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.apache.maven.wagon</groupId>
            <artifactId>wagon-ssh</artifactId>
            <version>2.5</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

looks like this is fixed in maven-site-plugin and wagon-ssh

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Already fixed as part of WAGON-424
