### ISSUE TITLE
[WAGON-356] java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#417]
**[Daniel Spilker](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daniel.spilker@hamburg.de)** opened **[WAGON-356](https://issues.apache.org/jira/browse/WAGON-356?redirect=false)** and commented

When performing a release the site deployment fails due to a ClassNotFoundException.

```
[INFO] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Nov 8, 2011 10:28:56 AM org.sonatype.guice.bean.reflect.NamedClass
[INFO] WARNING: Error injecting: org.apache.maven.wagon.providers.webdav.WebDavWagon
[INFO] com.google.inject.ProvisionException: Guice provision errors:
[INFO]
[INFO] 1) Error injecting constructor, java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
[INFO]   at org.apache.maven.wagon.providers.webdav.WebDavWagon.<init>(Unknown Source)
[INFO]   while locating org.apache.maven.wagon.providers.webdav.WebDavWagon
[INFO]
[INFO] [INFO] [ERROR]
1 error
[INFO] Unsupported protocol: 'dav' for site deployment to distributionManagement.site.url=dav:https://repository.coremedia.com/...
[INFO]  at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:977)
[INFO]  at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1003)
[INFO]  at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:47)
[INFO]  at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
[INFO]  at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:968)
[INFO]  at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1014)
[INFO]  at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:964)
[INFO]  at com.google.inject.Scopes$1$1.get(Scopes.java:59)
[INFO]  at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:79)
[INFO]  at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:53)
[INFO]  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
[INFO]  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:235)
[INFO]  at org.apache.maven.repository.legacy.DefaultWagonManager.getWagon(DefaultWagonManager.java:764)
[INFO]  at org.apache.maven.repository.legacy.DefaultWagonManager.getWagon(DefaultWagonManager.java:747)
[INFO]  at org.apache.maven.plugins.site.AbstractDeployMojo.getWagon(AbstractDeployMojo.java:354)
[INFO]  at org.apache.maven.plugins.site.AbstractDeployMojo.deploy(AbstractDeployMojo.java:264)
        at org.apache.maven.plugins.site.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:257)
[INFO]  at org.apache.maven.plugins.site.AbstractDeployMojo.execute(AbstractDeployMojo.java:165)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:597)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] Caused by: java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
[INFO]  at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:230)
[INFO]  at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
[INFO]  at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:112)
[INFO]  at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:275)
[INFO]  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:248)
[INFO]  at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
[INFO]  at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:131)
[INFO]  at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
[INFO]  at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.<clinit>(MultiThreadedHttpConnectionManager.java:70)
[INFO]  at org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.<init>(AbstractHttpClientWagon.java:181)
[INFO]  at org.apache.maven.wagon.providers.webdav.WebDavWagon.<init>(WebDavWagon.java:64)
[INFO]  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO]  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[INFO]  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[INFO]  at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
[INFO]  at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
[INFO]  at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
[INFO]  at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
[INFO]  at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:968)
[INFO]  at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1021)
[INFO]  at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:964)
[INFO]  ... 38 more
[INFO] Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
[INFO]  at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[INFO]  at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
[INFO]  at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
[INFO]  ... 59 more
[INFO] [INFO] Final Memory: 137M/219M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [WARNING] The requested profile "internal-licenses" could not be activated because it does not exist.
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.0:deploy (default-deploy) on project warp: Unsupported protocol: 'dav' for site deployment to distributionManagement.site.url=dav:https://repository.coremedia.com/... -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR]
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] [ERROR]
[INFO] [ERROR] After correcting the problems, you can resume the build with the command
[INFO] [ERROR]   mvn <goals> -rf :warp
```

My POM looks like this:

```
...
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.0</version>
          <dependencies>
            <dependency>
              <groupId>org.apache.maven.wagon</groupId>
              <artifactId>wagon-webdav-jackrabbit</artifactId>
              <version>2.0</version>
            </dependency>
          </dependencies>
        </plugin>
...
```

---

**Affects:** 2.0

**Issue Links:**
- [WAGON-409](https://issues.apache.org/jira/browse/WAGON-409) Wagon-webdav-jackrabbit throws Class Not Found Exception.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

can you try with adding it as an extension:

```xml
<build>
  <extensions>
    <extension>
   <groupId>org.apache.maven.wagon</groupId>
      <artifactId>wagon-webdav-jackrabbit</artifactId>
      <version>2.0</version>
    </extension>
  </extensions>
```

**Comment by jira-importer** [comment]
**[Daniel Spilker](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daniel.spilker@hamburg.de)** commented

It works for `mvn site site-deploy`, but I did not perform a release. I will report the result when I have built the next release in two weeks.

**Comment by jira-importer** [comment]
**[Ivo Maixner](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ivom)** commented

Also resolved by downgrading jackrabbit to 1.0.

**Comment by jira-importer** [comment]
**[Daniel Spilker](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daniel.spilker@hamburg.de)** commented

OK, it works when I put it into the extensions element. So we can close this issue.

**Comment by jira-importer** [comment]
**[Lorenzo Bigagli](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bigagli)** commented

I had the same problem with Maven 3.0.3, maven-site-plugin 3.1, wagon-webdav-jackrabbit 2.2.

I confirm that setting jackrabbit as an extension solves the problem.
However, I would avoid extensions and keep jackrabbit as a maven-site-plugin dependency, so I worked around the issue forcing slf4j 1.6.1 (the policy of binding changed with 1.6, see http://www.slf4j.org/codes.html#StaticLoggerBinder).

I suggest future versions of jackrabbit update their dependency on slf4j, to avoid all this.

\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
	\<artifactId>maven-site-plugin\</artifactId>
	\<version>3.1\</version>
	\<dependencies>
	        \
	\<dependency>
		\<groupId>org.apache.maven.wagon\</groupId>
		\<artifactId>wagon-webdav-jackrabbit\</artifactId>
		\<version>2.2\</version>
	\</dependency>
	\
	\<dependency>
			\<groupId>org.slf4j\</groupId>
			\<artifactId>slf4j-api\</artifactId>
			\<version>1.6.1\</version>
		\</dependency>
\</dependencies>
\</plugin>
