### ISSUE TITLE
[WAGON-378] NullPointerException in LightweightHttpWagon.openConnectionInternal()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#432]
**[Mark Zalavari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zalavaari)** opened **[WAGON-378](https://issues.apache.org/jira/browse/WAGON-378?redirect=false)** and commented

I got a NullPointerException when I try to create a connection with LightweightHttpWagon.

Exception in thread "main" java.lang.NullPointerException
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.openConnectionInternal(LightweightHttpWagon.java:277)
at org.apache.maven.wagon.AbstractWagon.openConnection(AbstractWagon.java:105)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:207)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:124)
at com.zalavaari.maven.linkeddata.util.MavenRepoLeecher.leech(MavenRepoLeecher.java:29)
at com.zalavaari.maven.linkeddata.Main.leech(Main.java:34)
at com.zalavaari.maven.linkeddata.Main.main(Main.java:16)

I can reproduce it in 2.2, 2.1 and 2.0.
1.0 seems okay.

I can create and attach a minimal project for reproducing the problem if needed, but as I see, the problem is trivial.

---

**Affects:** 2.2

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I wonder how do you construct your wagon http instance ?
Some fields need to use plexus injection mechanism !
Yes a project to reproduce please.

**Comment by jira-importer** [comment]
**[Mark Zalavari](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zalavaari)** commented

Thanks for the quick answer.

Then that's the problem.
I just instantiate a new LightweightHttpWagon, and try to connect with a given Repository.
So if I understand well, I shouldn't use wagon without plexus.
Sorry for the inconvenience, i will close the issue.
