### ISSUE TITLE
[WAGON-382] Provide a LightweightHttpWagon.setAuthenticator(LightweightHttpWagonAuthenticator) method

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#439]
**[Kabir Khan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabirkhan)** opened **[WAGON-382](https://issues.apache.org/jira/browse/WAGON-382?redirect=false)** and commented

Using this with aether we get

```
Downloading: http://repository.jboss.org/nexus/content/groups/developer/org/jboss/as/jboss-as-jmx/7.1.2.Final/jboss-as-jmx-7.1.2.Final.jar
org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss.as:jboss-as-jmx:jar:7.1.2.Final from/to jboss-developer (http://repository.jboss.org/nexus/content/groups/developer/): NullPointerException
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NullPointerException
	at org.apache.maven.wagon.providers.http.LightweightHttpWagon.openConnectionInternal(LightweightHttpWagon.java:277)
	at org.apache.maven.wagon.AbstractWagon.openConnection(AbstractWagon.java:116)
	at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:218)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:345)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon(WagonRepositoryConnector.java:385)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:571)
	... 4 more
```

There does not seem to be a way to set the authenticator field without using plexus

---
No further details from [WAGON-382](https://issues.apache.org/jira/browse/WAGON-382?redirect=false)

**Comment by jira-importer** [comment]
**[Kabir Khan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabirkhan)** commented

This affects 2.3, I don't seem to be able to edit the issue

**Comment by jira-importer** [comment]
**[Kabir Khan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabirkhan)** commented

https://jira.codehaus.org/browse/WAGON-378 explains what to do
