### ISSUE TITLE
[WAGON-392] Maven 3.0.5 regression in release:perform: "Host name may not be null"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#449]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** opened **[WAGON-392](https://issues.apache.org/jira/browse/WAGON-392?redirect=false)** and commented

With Maven 3.0.4 deploying to our Artifactory server from `release:perform` works fine:

```none
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ ... ---
Uploading: https://....artifactoryonline.com/.../releases/.../8/...-8.pom
Uploaded: https://....artifactoryonline.com/.../releases/.../8/...-8.pom (16 KB at 11.1 KB/sec)
```

But the same command in Maven 3.0.5 fails:

```none
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ ... ---
Uploading: https://....artifactoryonline.com/.../releases/.../8/...-8.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] ...
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project ...: Failed to deploy artifacts: Could not transfer artifact ...:...:pom:8 from/to ... (https://....artifactoryonline.com/.../releases): Host name may not be null -> [Help 1]
```

---

**Attachments:**
- [ssl.png](https://issues.apache.org/jira/secure/attachment/12720724/ssl.png) (_44.72 kB_)

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

If I log in to the *.artifactoryonline.com server from Chrome with the same username and password specified in the `<server>` in `settings.xml`, Chrome reports no problems with the SSL certificate.

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

With `-e`:

```none
java.lang.IllegalArgumentException: Host name may not be null
	at org.apache.maven.wagon.providers.http.httpclient.HttpHost.<init>(HttpHost.java:79)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:501)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:746)
	?
```

Debugging made considerably more complicated by lack of deployed `*-sources.jar` for shaded artifacts, but everything looks fine at line 746 at least. Using `-X` turned up nothing more of interest.

Setting `-Dmaven.wagon.http.ssl.insecure=true` (either on `mvn` command line, or in `$MAVEN_OPTS`) as per WAGON-385 did not help. I also tried `.allowall` and `.ignore.validity.dates` without luck.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

it's a sample https://....artifactoryonline.com  or you really have all dots ?

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

The actual host name, repo name, and group/artifactId are elided with ? since they are not publicly readable anyway.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

It looks http client moved to use URI to get the host.

```
        URI uri = new URI("https://foo_bar.online.com/snapshots/org/apache/archiva/redback/components/spring-utils/2.1-SNAPSHOT/maven-metadata.xml");

        String host = uri.getHost();

        uri = new URI("https://foo_bar.online.com");

        host = uri.getHost();
```

host is always null maybe an issue for URI class when host contains '_' ?

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

Some research e.g. in http://www.ietf.org/rfc/rfc2396.txt shows that underscore (`_`) is in fact not a valid character in host names. (`URI.getAuthority` returns the host name but `getHost` correctly refuses to interpret it.) So the deployment repository is in fact invalid, and the wagon just needs to emit a more helpful error message. Can downgrade the priority here.

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

The problem is with the host name `ACCOUNTNAME_jfrog.artifactoryonline.com`. JFrog also seems to accept `ACCOUNTNAME-jfrog.artifactoryonline.com` which is a legitimate hostname that Maven 3.0.5 can deploy to.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
