### ISSUE TITLE
[WAGON-443] WebDAV Wagon does not encode umlauts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#504]
**[Stephan Lau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=flatstep)** opened **[WAGON-443](https://issues.apache.org/jira/browse/WAGON-443?redirect=false)** and commented

I am not able to use wagon with files containing umlauts in their filename.
It seems like the url is not correctly encoded. Please have a look at the following stack trace:

> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy (default-deploy) on project solar-documentation: Execution default-deploy of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: Invalid uri 'http://data/bibliothek/solar-documentation/current/solar-documentation/referenz/_speichern_löschen.html': escaped absolute path not valid
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-deploy of goal org.apache.maven.plugins:maven-site-plugin:3.4:deploy failed: Invalid uri 'http://data/bibliothek/solar-documentation/current/solar-documentation/referenz/_speichern_löschen.html': escaped absolute path not valid
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
> ... 19 more
> Caused by: java.lang.IllegalArgumentException: Invalid uri 'http://data/bibliothek/solar-documentation/current/solar-documentation/referenz/_speichern_löschen.html': escaped absolute path not valid
> at org.apache.commons.httpclient.HttpMethodBase.\<init>(HttpMethodBase.java:222)
> at org.apache.commons.httpclient.methods.ExpectContinueMethod.\<init>(ExpectContinueMethod.java:93)
> at org.apache.commons.httpclient.methods.EntityEnclosingMethod.\<init>(EntityEnclosingMethod.java:119)
> at org.apache.commons.httpclient.methods.PutMethod.\<init>(PutMethod.java:76)
> at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:356)
> at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:324)
> at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:301)
> at org.apache.maven.wagon.providers.webdav.WebDavWagon.put(WebDavWagon.java:326)
> at org.apache.maven.wagon.providers.webdav.WebDavWagon.putDirectory(WebDavWagon.java:187)
> at org.apache.maven.wagon.providers.webdav.WebDavWagon.putDirectory(WebDavWagon.java:181)
> at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.push(AbstractDeployMojo.java:441)
> at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:323)
> at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.deployTo(AbstractDeployMojo.java:284)
> at org.apache.maven.plugins.site.deploy.AbstractDeployMojo.execute(AbstractDeployMojo.java:166)
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
> ... 20 more

---

**Affects:** 2.9

**Issue Links:**
- [WAGON-538](https://issues.apache.org/jira/browse/WAGON-538) Basic authentication fails if the password contains non-ASCII characters
 (_**"duplicates"**_)
- [WAGON-488](https://issues.apache.org/jira/browse/WAGON-488) Upgrade WebDAV Wagon to a more recent HttpClient version (4.5.3)
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Is this one still valid?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No reaction for two months.
