### ISSUE TITLE
[WAGON-461] URL string not properly encoded by webdav

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#519]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** opened **[WAGON-461](https://issues.apache.org/jira/browse/WAGON-461?redirect=false)** and commented

wagon-webdav is not calling EncodingUtil prior to instantiating MkColMethod which results in

```java
Caused by: java.lang.IllegalArgumentException: Invalid uri 'https://snafu.sharefile-webdav.com/Shared Folders/Fit - Expert Services/IBM/': escaped absolute path not valid
```

when there are special characters in the URI string.

Changing line 153 of org.apache.maven.wagon.providers.webdav.WebDavWagon from

```java
method = new MkColMethod( url );
```

to

```java
method = new MkColMethod( EncodingUtil.encodeURLToString( url ) );
```

solves the issue although you may want to fix it elsewhere in the flow.

---

**Affects:** 2.10

**Attachments:**
- [logs.zip](https://issues.apache.org/jira/secure/attachment/12823980/logs.zip) (_7.06 kB_)

**Issue Links:**
- [WAGON-488](https://issues.apache.org/jira/browse/WAGON-488) Upgrade WebDAV Wagon to a more recent HttpClient version (4.5.3)
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Where does the URI come from, especially the path (`/Shared Folders/Fit - Expert Services/IBM`)? It pretty much looks like invalid input from the POM.

**Comment by jira-importer** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

It's from Sharefile and it is a valid Sharefile webdav URI. Adding the encodeURLToString results in a successful file transfer into the target Sharefile folder. I can send you a Pull request with my working change if you like.

Putting debug statements into WebDavWagon shows that the problem is the code is not URL encoding the spaces which then causes HttpMethodBase to blow-up.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This is actually what I wanted to see. The URI ist not valid, see [here](http://stackoverflow.com/a/497972/696632) for a citation of the appropriate RFC.

**Comment by jira-importer** [comment]
**[Mike Summers](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=msummers)** commented

Right, I tried that originally however pre-encoding the URI in the pom doesn't help as the URI is finally encoded farther down the code chain which then encodes the encoding.

pom.xml

```xml
<url>dav:https://snafu.sharefile-webdav.com/Shared%20Folders/Fit%20-%20Expert%20Services/IBM</url>
```

Stack trace:

```java
[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:upload-single (upload-assembly) on project synthetics-monitor-plugin: Error handling resource: Failed to transfer file: https://snafu.sharefile-webdav.com/Shared%2520Folders/Fit%2520-%2520Expert%2520Services/IBM/synthetics-monitor-plugin-1.0.0.jar. Return code is: 409 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:upload-single (upload-assembly) on project synthetics-monitor-plugin: Error handling resource
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error handling resource
	at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:68)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
```

Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: https://snafu.sharefile-webdav.com/Shared%2520Folders/Fit%2520-%2520Expert%2520Services/IBM/synthetics-monitor-plugin-1.0.0.jar. Return code is: 409

```java
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:417)
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:324)
at org.apache.maven.wagon.providers.webdav.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:301)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.put(WebDavWagon.java:326)
at org.codehaus.mojo.wagon.UploadSingleMojo.execute(UploadSingleMojo.java:70)
at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:64)
... 22 more
```

wagon-ftp working on the unencoded pom URI is also an indication that pre-encoding the URI in the pom is probably not the right direction. I would think that both wagon-ftp and wagon-webdav would have the same interface contract with the plugin, but perhaps not.

Also, pre-encoding the URI doesn't make a lot of sense given that adding the encoding call to WebDavWagon does work.

If you have an alternate URI encoding you're thinking of please forward it and I'll give it a try.

Thanks.
