### ISSUE TITLE
[WAGON-466] wagon-ssh: Better error message when ssh account is locked

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#523]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** opened **[WAGON-466](https://issues.apache.org/jira/browse/WAGON-466?redirect=false)** and commented

When wagon-ssh encounter none prompt eror ( like account is lock) it throws

Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
at org.apache.maven.wagon.providers.ssh.jsch.interactive.UserInfoUIKeyboardInteractiveProxy.promptKeyboardInteractive(UserInfoUIKeyboardInteractiveProxy.java:53)
at com.jcraft.jsch.UserAuthKeyboardInteractive.start(UserAuthKeyboardInteractive.java:141)
at com.jcraft.jsch.Session.connect(Session.java:470)
at com.jcraft.jsch.Session.connect(Session.java:183)
at org.apache.maven.wagon.providers.ssh.jsch.AbstractJschWagon.openConnectionInternal(AbstractJschWagon.java:254)
at org.apache.maven.wagon.AbstractWagon.openConnection(AbstractWagon.java:115)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:215)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:152)

This is due to empty array UserInfoUIKeyboardInteractiveProxy

The solution is not handle the empty promt

---

**Affects:** 2.10

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

fixed at

https://git1-us-west.apache.org/repos/asf?p=maven-wagon.git;a=commitdiff;h=412c0fbd7fb0107804080bb4b58bb0f249c0768a
