### ISSUE TITLE
[WAGON-592] Wagon fails when compiled on Java 9+ and run on Java 8 due to JDK API breakage

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#643]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[WAGON-592](https://issues.apache.org/jira/browse/WAGON-592?redirect=false)** and commented

When Wagon is compiled with Java 9+ and run with Maven core or something else with Java 8 one can observe the following:

```
[INFO] Running org.apache.maven.repository.internal.DefaultArtifactDescriptorReaderTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.802 s <<< FAILURE! - in org.apache.maven.repository.internal.DefaultArtifactDescriptorReaderTest
[ERROR] testMng5459(org.apache.maven.repository.internal.DefaultArtifactDescriptorReaderTest)  Time elapsed: 0.787 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReaderTest.testMng5459(DefaultArtifactDescriptorReaderTest.java:56)

[INFO] Running org.apache.maven.repository.internal.DefaultModelResolverTest
[ERROR] Tests run: 10, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.354 s <<< FAILURE! - in org.apache.maven.repository.internal.DefaultModelResolverTest
[ERROR] testResolveDependencySuccessfullyResolvesExistingDependencyWithoutRange(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.038 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveDependencySuccessfullyResolvesExistingDependencyWithoutRange(DefaultModelResolverTest.java:198)

[ERROR] testResolveParentSuccessfullyResolvesExistingParentWithoutRange(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.031 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveParentSuccessfullyResolvesExistingParentWithoutRange(DefaultModelResolverTest.java:117)

[ERROR] testResolveParentSuccessfullyResolvesExistingParentUsingHighestVersion(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.047 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveParentSuccessfullyResolvesExistingParentUsingHighestVersion(DefaultModelResolverTest.java:128)

[ERROR] testResolveDependencyThrowsUnresolvableModelExceptionWhenNoMatchingVersionFound(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.038 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveDependencyThrowsUnresolvableModelExceptionWhenNoMatchingVersionFound(DefaultModelResolverTest.java:160)

[ERROR] testResolveDependencySuccessfullyResolvesExistingDependencyUsingHighestVersion(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.031 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveDependencySuccessfullyResolvesExistingDependencyUsingHighestVersion(DefaultModelResolverTest.java:209)

[ERROR] testResolveDependencyThrowsUnresolvableModelExceptionWhenUsingRangesWithoutUpperBound(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.032 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveDependencyThrowsUnresolvableModelExceptionWhenUsingRangesWithoutUpperBound(DefaultModelResolverTest.java:180)

[ERROR] testResolveParentThrowsUnresolvableModelExceptionWhenNoMatchingVersionFound(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.037 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveParentThrowsUnresolvableModelExceptionWhenNoMatchingVersionFound(DefaultModelResolverTest.java:79)

[ERROR] testResolveParentThrowsUnresolvableModelExceptionWhenUsingRangesWithoutUpperBound(org.apache.maven.repository.internal.DefaultModelResolverTest)  Time elapsed: 0.016 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultModelResolverTest.testResolveParentThrowsUnresolvableModelExceptionWhenUsingRangesWithoutUpperBound(DefaultModelResolverTest.java:99)

[INFO] Running org.apache.maven.repository.internal.DefaultVersionResolverTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.apache.maven.repository.internal.DefaultVersionResolverTest
[ERROR] testResolveSeparateInstalledClassifiedNonUniqueVersionedArtifacts(org.apache.maven.repository.internal.DefaultVersionResolverTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.DefaultVersionResolverTest.testResolveSeparateInstalledClassifiedNonUniqueVersionedArtifacts(DefaultVersionResolverTest.java:59)

[INFO] Running org.apache.maven.repository.internal.MavenRepositorySystemUtilsTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.maven.repository.internal.MavenRepositorySystemUtilsTest
[INFO] Running org.apache.maven.repository.internal.RemoteSnapshotMetadataTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.apache.maven.repository.internal.RemoteSnapshotMetadataTest
[INFO] Running org.apache.maven.repository.internal.RepositorySystemTest
[ERROR] Tests run: 11, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.271 s <<< FAILURE! - in org.apache.maven.repository.internal.RepositorySystemTest
[ERROR] testCollectDependencies(org.apache.maven.repository.internal.RepositorySystemTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.RepositorySystemTest.testCollectDependencies(RepositorySystemTest.java:122)

[ERROR] testReadArtifactDescriptor(org.apache.maven.repository.internal.RepositorySystemTest)  Time elapsed: 0.028 s  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at org.apache.maven.repository.internal.RepositorySystemTest.testReadArtifactDescriptor(RepositorySystemTest.java:63)
```

A similar issue has been reported here: https://github.com/hazelcast/hazelcast/issues/14214#issue-387286620

---

**Affects:** 3.4.0

**Issue Links:**
- [WAGON-590](https://issues.apache.org/jira/browse/WAGON-590) Maven 3.5.0+ doesn't seem to send credentials after 301/302 HTTP redirect

**Remote Links:**
- [Affected methods
](https://github.com/mongodb/mongo-java-driver/commit/21c91bd364d38489e0bbe2e390efdb3746ee3fff)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [92c0d2a858a38d9b3d0aefc0f9298d5c31c7e508](https://gitbox.apache.org/repos/asf?p=maven-wagon.git;a=commit;h=92c0d2a858a38d9b3d0aefc0f9298d5c31c7e508).
