### ISSUE TITLE
[WAGON-266] Wagon ftp error using Mac OS

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#667]
**[Daniel Maier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dmaier)** opened **[WAGON-266](https://issues.apache.org/jira/browse/WAGON-266?redirect=false)** and commented

Hi,
I tried to upload my site using wagon-ftp. With windows it works without problems. But if I use Mac OS, I get the following Error Message:

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection()V
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.AbstractMethodError: org.apache.maven.wagon.providers.ftp.FtpWagon.openConnection()V
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:106)
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:184)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 seconds
[INFO] Finished at: Tue May 19 11:09:12 CEST 2009
[INFO] Final Memory: 32M/63M

Any hints what causes this error?

Thanks
Daniel Maier

---
No further details from [WAGON-266](https://issues.apache.org/jira/browse/WAGON-266?redirect=false)

**Comment by jira-importer** [comment]
**[Daniel Peterson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dpeterson)** commented

Yeah, I'm getting this one too, although it used to work just fine a week ago. Still running the same version of the ftp-wagon (1.0-beta5) and Maven (2.0.10) as when it was previously working. Weird...

**Comment by jira-importer** [comment]
**[Daniel Peterson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dpeterson)** commented

As an addendum to this, I believe that I have updated to Leopard 10.5.7 in the meantime. Possible cause? Details:

Maven version: 2.0.10
Java version: 1.5.0_16
OS name: "mac os x" version: "10.5.7" arch: "i386" Family: "unix"

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

1.0-beta-3+ do not work with Maven 2.0.x. You can use the 1.0-beta-2 FTP wagon, or switch to Maven 2.2.1.

Cheers,
Brett
