### ISSUE TITLE
[WAGON-40] Does not deploy to existing folder

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#691]
**[Andreas Guther](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aguther)** opened **[WAGON-40](https://issues.apache.org/jira/browse/WAGON-40?redirect=false)** and commented

I have mapped a drive to our site deployment server on a windows 2003 server.  The deploy works fine if the target folder does not exist.  If the project was previously deployed the deploy target will fail with the error as included below.  I would expect that the deploy overwrites the content in an existing folder.

C:\workspace\dev.ztel.mt.trunk>mvn site:deploy -e
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'site'.
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building zTelligence
  [INFO]    task-segment: [site:deploy]
  [INFO] ----------------------------------------------------------------------------
  [INFO] [site:deploy]
  file://W:/projects/ztel-trunk - Session: Opened
  file://W:/projects/ztel-trunk - Session: Disconnecting
  file://W:/projects/ztel-trunk - Session: Disconnected
  [INFO] ----------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ----------------------------------------------------------------------------
  [INFO] Error uploading site

Embedded error: Could not make directory 'W:\projects\ztel-trunk\.'.
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error uploading site
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:485)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:455)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error uploading site
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:162)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
... 16 more
Caused by: org.apache.maven.wagon.TransferFailedException: Could not make directory 'W:\projects\ztel-trunk\.'.
at org.apache.maven.wagon.providers.file.FileWagon.putDirectory(FileWagon.java:113)
at org.apache.maven.plugins.site.SiteDeployMojo.execute(SiteDeployMojo.java:154)
... 18 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Sat Mar 25 09:22:14 PST 2006
[INFO] Final Memory: 4M/508M
[INFO] ------------------------------------------------------------------------

---

**Attachments:**
- [site.error.txt](https://issues.apache.org/jira/secure/attachment/12720685/site.error.txt) (_11.83 kB_)

**Comment by jira-importer** [comment]
**[Andreas Guther](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aguther)** commented

I need to add that I have the following configuration for the distribution management:

\<distributionManagement>
		\<site>
			\<id>ztel.trunk\</id>
			\<name>zTelligence Trunk\</name>
			\<url>file://W:/projects/ztel-trunk\</url>
		\</site>
	\</distributionManagement>

**Comment by jira-importer** [comment]
**[Jesse McConnell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmcconnell)** commented

Caused by: org.apache.maven.wagon.TransferFailedException: Could not make directory 'W:\projects\ztel-trunk\.'.
at org.apache.maven.wagon.providers.file.FileWagon.putDirectory(FileWagon.java:113)

this looks like more of a wagon issue so moving it over to there

**Comment by jira-importer** [comment]
**[Andreas Guther](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aguther)** commented

The described behavior seems to be gone with Maven 2.0.4.  Today I used the command line to distribute different sites multiple times and all deployments went through without problems.  I still have the same scenario with deploying via the file system and mapped drives to a different server.

**Comment by jira-importer** [comment]
**[Henry S. Isidro](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hisidro)** commented

It works for me as well. Tried it on a mapped drive on a Windows 2003 Server and Maven 2.0.4. Resolving this issue now.

**Comment by jira-importer** [comment]
**[Henry S. Isidro](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hisidro)** commented

Cannot reproduce described behavior. Environment: WinXP, Windows 2003 Server, Maven 2.0.4
