### ISSUE TITLE
[WAGON-229] AbstractMethodError when deploying with Continuum

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#701]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** opened **[WAGON-229](https://issues.apache.org/jira/browse/WAGON-229?redirect=false)** and commented

I try to deploy my parent pom.xml with Continuum. I'm using Maven 2.0.7 and I added a build extension in the pom : wagon-webdav-jackrabbit:1.0-beta-3

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-deploy-plugin:2.3:deploy' -->
[DEBUG]   (f) artifact = com.mycompany:parent:pom:1.1.0-SNAPSHOT
[DEBUG]   (f) attachedArtifacts = []
[DEBUG]   (f) deploymentRepository = [mycompany.corporate.snapshots] -> dav:http://archiva-bu.mycompany.fr:8090/archiva/repository/mycompany.corporate.snapshots
[DEBUG]   (s) localRepository = [local] -> file:///home/continuum/.m2/repository
[DEBUG]   (f) packaging = pom
[DEBUG]   (f) pomFile = /var/lib/continuum/working-directory/66/pom.xml
[DEBUG]   (f) updateReleaseInfo = false
[DEBUG]   - end configuration --
[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] Retrieving previous build number from mycompany.corporate.snapshots
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.AbstractMethodError
at org.apache.maven.wagon.AbstractWagon.connect(AbstractWagon.java:143)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:235)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:153)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:152)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 1.0-beta-3

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

the beta-3 wagons don't work with older versions of Maven as detailed in the release notes.

You should continue using wagon-webdav 1.0-beta-2, or you can simply use http instead of dav:http in most cases.

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

OK, thanks for the information. I will try to migrate to Maven 2.0.9.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

actually, beta-3 was first bundled with 2.0.10 (now in RC mode). Is there a specific fix you are in need of? Archiva does work with the normal built in http of all Maven versions in most cases.

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

Here is the full story:

First my build failed with:

[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] Retrieving previous build number from mycompany.corporate.snapshots
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Unsupported Protocol: 'dav': Cannot find wagon which supports the requested protocol: dav

Component descriptor cannot be found in the component repository: org.apache.maven.wagon.Wagondav.

So I added the wagon-webdav:1.0-beta-2 to my pom. Then I got:

[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] Retrieving previous build number from mycompany.corporate.snapshots
Uploading: http://archiva-bu.mycompany.fr:8090/archiva/repository/mycompany.corporate.snapshots/com/mycompany/parent/1.1.0-SNAPSHOT/parent-1.1.0-20080721.132243-3.pom
21 juil. 2008 15:22:44 org.apache.commons.httpclient.HttpMethodBase processAuthenticationResponse
INFO: Already tried to authenticate with 'Repository Repository mycompany Snapshots' authentication realm at archiva-bu.mycompany.fr, but still receiving: HTTP/1.1 401 User+Credentials+Invalid
21 juil. 2008 15:22:44 org.apache.commons.httpclient.HttpMethodBase processAuthenticationResponse
INFO: Already tried to authenticate with 'Repository Repository mycompany Snapshots' authentication realm at archiva-bu.mycompany, but still receiving: HTTP/1.1 401 User+Credentials+Invalid
21 juil. 2008 15:22:44 org.apache.commons.httpclient.HttpMethodBase processAuthenticationResponse
INFO: Already tried to authenticate with 'Repository Repository mycompany Snapshots' authentication realm at archiva-bu.mycompany.fr, but still receiving: HTTP/1.1 401 User+Credentials+Invalid
21 juil. 2008 15:22:44 org.apache.commons.httpclient.HttpMethodBase processAuthenticationResponse
INFO: Already tried to authenticate with 'Repository Repository mycompany Snapshots' authentication realm at archiva-bu.mycompany.fr, but still receiving: HTTP/1.1 401 User+Credentials+Invalid
21 juil. 2008 15:22:45 org.apache.commons.httpclient.HttpMethodBase processAuthenticationResponse
INFO: Already tried to authenticate with 'Repository Repository mycompany Snapshots' authentication realm at archiva-bu.mycompany.fr, but still receiving: HTTP/1.1 401 User+account+is+locked
21 juil. 2008 15:22:45 org.apache.commons.httpclient.HttpMethodBase processRequest
INFO: Recoverable exception caught when processing request
21 juil. 2008 15:22:45 org.apache.commons.httpclient.HttpMethodBase processRequest
ATTENTION: Recoverable exception caught but MethodRetryHandler.retryMethod() returned false, rethrowing exception
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error deploying artifact: Failed to create destination WebDAV collection (directory): /archiva/repository/mycompany.corporate.snapshots/com/capgemini/sud/parent/1.1.0-SNAPSHOT

java.net.SocketException: Connection reset

So I decided to try to update to latest available wagon. But now I read the log carefully I think there is an authentification issue.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

yes, you are right. If you have further problems drop us a note at either the Archiva or Maven lists - I'll close this for the time being.
