### ISSUE TITLE
[WAGON-221] removeCheckoutDirectory throws NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#731]
**[Arnold Reuser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=areuser)** opened **[WAGON-221](https://issues.apache.org/jira/browse/WAGON-221?redirect=false)** and commented

[INFO] [deploy:deploy]
altDeploymentRepository = null
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.codehaus.plexus.util.FileUtils.deleteDirectory(FileUtils.java:1219)
at org.apache.maven.wagon.providers.scm.ScmWagon.removeCheckoutDirectory(ScmWagon.java:180)
at org.apache.maven.wagon.providers.scm.ScmWagon.closeConnection(ScmWagon.java:526)
at org.apache.maven.wagon.AbstractWagon.disconnect(AbstractWagon.java:153)
at org.apache.maven.artifact.manager.DefaultWagonManager.disconnectWagon(DefaultWagonManager.java:703)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:291)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:160)

The NPE is caused by removeCheckoutDirectory, probably because checkoutDirectory is null.

private void removeCheckoutDirectory()
throws ConnectionException
{
try
{
FileUtils.deleteDirectory( checkoutDirectory );
}
catch ( IOException e )
{
throw new ConnectionException( "Unable to cleanup checkout directory", e );
}
}

Please let me known when additional information is required.

---

**Affects:** 1.0-beta-3

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

already fixed by Joakim in r739606
