### ISSUE TITLE
[WAGON-190] scp intermittently failing deploying artifact

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#739]
**[Joe Futrelle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=futrelle)** opened **[WAGON-190](https://issues.apache.org/jira/browse/WAGON-190?redirect=false)** and commented

Some of the time, deploying artifacts fails during the scp transfer. The bottom of the stack trace is reproduced below. If I run the m2 deploy enough times, it succeeds; not sure why.

This is not an unknown issue with Jsch; apparently client code can cause behavior like this if it doesn't dispose of connections properly. Possibly a plugin that's runs before the deploy phase is messing up the connection state somehow?

Caused by: org.apache.maven.wagon.TransferFailedException: Error occured while deploying 'ncsa/gsbt/1.0-SNAPSHOT/gsbt-1.0-20050728.190330-38.pom.sha1' to remote repository: scp://chasm.ncsa.uiuc.edu//home/futrelle/m2/repository
at org.apache.maven.wagon.providers.ssh.ScpWagon.put(ScpWagon.java:331)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:167)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:91)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:73)
... 17 more
Caused by: com.jcraft.jsch.JSchException: session is down
at com.jcraft.jsch.Channel.connect(Unknown Source)
at org.apache.maven.wagon.providers.ssh.ScpWagon.put(ScpWagon.java:271)
... 20 more

---

**Issue Links:**
- [MNG-1242](https://issues.apache.org/jira/browse/MNG-1242) Can't deploy with scp wagon provider
 (_**"is duplicated by"**_)
- [WAGON-88](https://issues.apache.org/jira/browse/WAGON-88) Evaluate commons vfs to use for file system operations

10 votes, 16 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

unfortunately this updated JAR hangs the scp knownhosts tests for me (as does 0.1.22, but not 0.1.21).

I haven't seen the session is down issue since restructuring. I will see how we go.

You've done an excellent job here - would you be able to continue following through on this?

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Mario Ivankovits from commons-vfs, they use scp with jsch, said

I've never seen this problem and there were no reports like this.

Could it be, that the time after creating the session and requesting a channel is too long idle and thus the server ended it?
Just a wild guess ...

**Comment by jira-importer** [comment]
**[Michael Fiedler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michaeljf)** commented

I am getting this error again.  I used ssh-keygen to make a private & public file to get around the deploy hanging.

I am using maven2 when I ran release:deploy on a win xp, sp2 machine to a w2k host via OpenSSH.

My project structure is:
modules
- util
- exceptions
- modC
- modD

I was able to get the following files uploaded before the error:
[INFO] [deploy:deploy]
host - private computer system & equipment: Uploading: scp://host/com/werner/modules/1.0-QA/modules-1.0-QA.pom
...
host - private computer system & equipment: host - private computer system & equipment: Uploading: scp://host/com/werner/modules/1.0-QA/modules-1.0-QA-javadoc.pom
...
[INFO] [deploy:deploy]
host - private computer system & equipment: Uploading: scp://host/com/werner/util/1.0-QA/util-1.0-QA.jar
...
host - private computer system & equipment: host - private computer system & equipment: Uploading: scp://host/com/werner/util/1.0-QA/util-1.0-QA-javadoc.jar
...
host - private computer system & equipment: Uploading: scp://host/com/werner/util/1.0-QA/util-1.0-QA-sources.jar
...
[INFO] [deploy:deploy]
host - private computer system & equipment: Uploading: scp://host/com/werner/exception/1.0-QA/exception-1.0-QA.jar
...
67K uploaded
[INFO] Retrieving previous metadata from M2_repo
host - private computer system & equipment: [INFO] Uploading repository metadata for: 'artifact com.werner:exception'
host - private computer system & equipment: [INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error installing artifact's metadata: Error while deploying metadata: Did receive proper ACK: '1'

Thank you, Michael

**Comment by jira-importer** [comment]
**[Grégory Joseph](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gjoseph)** commented

I'm getting this error as well when deploying a war which is +/-20mb in size, while other smaller jar artifacts cause no problems.

**Comment by jira-importer** [comment]
**[Grégory Joseph](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gjoseph)** commented

Oh gosh, in my case, the distant repo's disk was full. However, it'd be nice if this kind of meaningful information was reported in the buid failure message :)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

There's other pure java ssh implementation
http://www.ganymed.ethz.ch/ssh2/

**Comment by jira-importer** [comment]
**[Arik Kfir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arikkfir)** commented

Perhaps the problem is that jsch's output/input streams are not delegated to the console? I've noticed problems like this whenever input is needed in the remote system...

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I'm seeing this on my laptop but not on my desktop.  Odd.  The latest version, 0.1.24, has a bug fix that mentions sessions.  I'd test it out but it's not on central yet.

http://www.jcraft.com/jsch/ChangeLog

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

jsch 0.1.24 does not correct the issue

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'm speculating this is fixed as I've made it through 10 sequential projects twice after recent changes. Will wait for testing.

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

Brett,

i've just svn up and bootstrapped the whole m2 trunk and I've then tried to deploy some cargo jar. Unfortunately it failed with the "session is down" problem:

C:\dev\cargo\trunk\core\api\util>mvn clean deploy
[INFO] Scanning for projects...
[INFO] snapshot org.apache.maven.wagon:wagon-ssh-external:1.0-alpha-6-SNAPSHOT: checking for updates from central
[INFO] snapshot org.apache.maven.wagon:wagon-ssh-external:1.0-alpha-6-SNAPSHOT: checking for updates from cargo m2 release reposit
ory
[INFO] snapshot org.apache.maven.wagon:wagon-ssh-external:1.0-alpha-6-SNAPSHOT: checking for updates from maven-snapshot
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-ssh-external/1.0-alpha-6-SNAPSHOT/wagon-ssh-e
xternal-1.0-alpha-6-20060105.062346-5.pom
971b downloaded
[INFO] snapshot org.apache.maven.wagon:wagon-providers:1.0-alpha-6-SNAPSHOT: checking for updates from central
[INFO] snapshot org.apache.maven.wagon:wagon-providers:1.0-alpha-6-SNAPSHOT: checking for updates from cargo m2 release repository

[INFO] snapshot org.apache.maven.wagon:wagon-providers:1.0-alpha-6-SNAPSHOT: checking for updates from maven-snapshot
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-providers/1.0-alpha-6-SNAPSHOT/wagon-provider
s-1.0-alpha-6-20060105.062346-6.pom
1K downloaded
[INFO] snapshot org.apache.maven.wagon:wagon:1.0-alpha-6-SNAPSHOT: checking for updates from central
[INFO] snapshot org.apache.maven.wagon:wagon:1.0-alpha-6-SNAPSHOT: checking for updates from cargo m2 release repository
[INFO] snapshot org.apache.maven.wagon:wagon:1.0-alpha-6-SNAPSHOT: checking for updates from maven-snapshot
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon/1.0-alpha-6-SNAPSHOT/wagon-1.0-alpha-6-200601
05.062346-7.pom
4K downloaded
[INFO] snapshot org.apache.maven.wagon:wagon-provider-api:1.0-alpha-6-SNAPSHOT: checking for updates from central
[INFO] snapshot org.apache.maven.wagon:wagon-provider-api:1.0-alpha-6-SNAPSHOT: checking for updates from cargo m2 release reposit
ory
[INFO] snapshot org.apache.maven.wagon:wagon-provider-api:1.0-alpha-6-SNAPSHOT: checking for updates from maven-snapshot
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6-SNAPSHOT/wagon-provi
der-api-1.0-alpha-6-20060105.062346-7.pom
598b downloaded
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-6-SNAPSHOT/wagon-provi
der-api-1.0-alpha-6-20060105.062346-7.jar
41K downloaded
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-ssh-external/1.0-alpha-6-SNAPSHOT/wagon-ssh-e
xternal-1.0-alpha-6-20060105.062346-5.jar
9K downloaded
[INFO] ----------------------------------------------------------------------------
[INFO] Building Cargo Core Util API
[INFO]    task-segment: [clean, deploy]
[INFO] ----------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory C:\dev\cargo\trunk\core\api\util\target
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:compile]
Compiling 10 source files to C:\dev\cargo\trunk\core\api\util\target\classes
[INFO] [resources:testResources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:testCompile]
Compiling 1 source file to C:\dev\cargo\trunk\core\api\util\target\test-classes
[INFO] [surefire:test]
[INFO] Setting reports dir: C:\dev\cargo\trunk\core\api\util\target/surefire-reports
battery = null(org.apache.maven.surefire.battery.DirectoryBattery)

---

T E S T S

---

battery = null(org.apache.maven.surefire.battery.JUnitBattery)
[surefire] Running org.codehaus.cargo.util.Base64Test
[surefire] Tests run: 1, Failures: 0, Errors: 0, Time elapsed: 0,04 sec

Results :
[surefire] Tests run: 1, Failures: 0, Errors: 0

[INFO] [jar:jar]
[INFO] Building jar: C:\dev\cargo\trunk\core\api\util\target\cargo-core-api-util-0.8-SNAPSHOT.jar
[INFO] [install:install]
[INFO] Installing C:\dev\cargo\trunk\core\api\util\target\cargo-core-api-util-0.8-SNAPSHOT.jar to C:\Documents and Settings\Vincen
t Massol\.m2\repository\org\codehaus\cargo\cargo-core-api-util\0.8-SNAPSHOT\cargo-core-api-util-0.8-SNAPSHOT.jar
[INFO] [deploy:deploy]
[INFO] Retrieving previous build number from cargo-snapshot
The authenticity of host 'beaver.codehaus.org' can't be established.
RSA key fingerprint is 28:5c:69:90:31:43:99:f2:2c:85:33:86:44:02:91:3b.
Are you sure you want to continue connecting? (yes/no): yes
Uploading: scp://beaver.codehaus.org/home/projects/cargo/dist2-snapshot/org/codehaus/cargo/cargo-core-api-util/0.8-SNAPSHOT/cargo-
core-api-util-0.8-20060105.080831-1.jar
10K uploaded
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error deploying artifact: Error performing commands for file transfer

session is down
[INFO] ----------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 36 seconds
[INFO] Finished at: Thu Jan 05 09:08:51 CET 2006
[INFO] Final Memory: 5M/13M
[INFO] ----------------------------------------------------------------------------

C:\dev\cargo\trunk\core\api\util>

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Vincent: the fix is not on trunk. Please check $M2_HOME/lib includes the snapshot and let me know.

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

Brett: oh sorry. I just had 2 minutes this morning before going to work and I wanted to try your changes but I failed to notice your email explaining how to install the new stuff... I've installed it now and it's been working fine so far so that's great!

**Comment by jira-importer** [comment]
**[Kenneth Baltz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kcbaltz@yahoo.com)** commented

My initial experience with this bug is still true (see http://jira.codehaus.org/browse/WAGONSSH-28#action_51352).  This works for me in Solaris 10, but not Solaris 9.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

K.C. - this seems like a specific problem on Solaris 9 then (I have no environment to reproduce that on), and you haven't stated your exact problem (is it session is down? are you using maven 2.0.2 with the latest deploy plugin?) If so, please file a new issue for it. I consider this particular one resolved.
