### ISSUE TITLE
[WAGON-168] build error while building for a corporate

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#742]
**[deepak chavan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=deepak_ptg)** opened **[WAGON-168](https://issues.apache.org/jira/browse/WAGON-168?redirect=false)** and commented

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------

---

constituent[0]: file:/maven-2.0.6/lib/maven-core-2.0.6-uber.jar
constituent[1]: file:/root/.m2/repository/org/apache/maven/wagon/wagon-ssh-common/1.0-beta-2/wagon-ssh-common-1.0-beta-2.jar

---

java.lang.NullPointerException
at org.apache.maven.usability.MojoExecutionExceptionDiagnoser.diagnose(MojoExecutionExceptionDiagnoser.java:64)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:84)
at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:711)
at org.apache.maven.DefaultMaven.logError(DefaultMaven.java:656)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:131)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [WAGON-168](https://issues.apache.org/jira/browse/WAGON-168?redirect=false)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this appears to be something in your maven environment - more information would be needed. Please post to the wagon-dev@maven.apache.org list if you still have this problem
