### ISSUE TITLE
[WAGON-236] LightweightHttpWagon is not using proxy settings

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#745]
**[Thomas BELOT](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.belot)** opened **[WAGON-236](https://issues.apache.org/jira/browse/WAGON-236?redirect=false)** and commented

protected method "openConnectionInternal" which sets proxy definition is not called from within the class.
It's called by parent AbstractWagon#openConnection() which is called by AbstractWagon#connect
But none is called when coming from DefaultRepositoryProxyConnectors#transferSimpleFile

I "suggest" filling (my) RFE [WAGON-235]

See archiva 1.1 stack trace below :
2008-08-05 10:56:04,228 [TP-Processor3] DEBUG org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors  - Full stack trace
org.apache.maven.archiva.proxy.ProxyException: Download failure on resource http://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.pom:Error transferri
ng file
at org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors.transferSimpleFile(DefaultRepositoryProxyConnectors.java:747)
at org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors.transferFile(DefaultRepositoryProxyConnectors.java:564)
at org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors.fetchFromProxies(DefaultRepositoryProxyConnectors.java:171)
at org.apache.maven.archiva.webdav.ArchivaDavResourceFactory.applyServerSideRelocation(ArchivaDavResourceFactory.java:602)
at org.apache.maven.archiva.webdav.ArchivaDavResourceFactory.fetchContentFromProxies(ArchivaDavResourceFactory.java:518)
at org.apache.maven.archiva.webdav.ArchivaDavResourceFactory.doGet(ArchivaDavResourceFactory.java:423)
at org.apache.maven.archiva.webdav.ArchivaDavResourceFactory.createResource(ArchivaDavResourceFactory.java:251)
at org.apache.maven.archiva.webdav.RepositoryServlet.service(RepositoryServlet.java:119)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
at com.opensymphony.webwork.dispatcher.FilterDispatcher.doFilter(FilterDispatcher.java:189)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:39)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
at com.opensymphony.webwork.dispatcher.ActionContextCleanUp.doFilter(ActionContextCleanUp.java:88)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:199)
at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:282)
at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:776)
at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:706)
at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:898)
at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
at java.lang.Thread.run(Thread.java:595)
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:136)
at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors.transferSimpleFile(DefaultRepositoryProxyConnectors.java:704)
... 32 more
Caused by: java.net.ConnectException: Connection timed out
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
at java.net.Socket.connect(Socket.java:516)
at java.net.Socket.connect(Socket.java:466)
at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:365)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:477)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:214)
at sun.net.www.http.HttpClient.New(HttpClient.java:287)
at sun.net.www.http.HttpClient.New(HttpClient.java:299)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:796)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:748)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:673)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:917)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:115)
... 36 more
2008-08-05 10:56:04,230 [TP-Processor3] DEBUG org.apache.maven.archiva.proxy.DefaultRepositoryProxyConnectors  - Path [junit/junit/3.8.1/junit-3.8.1.pom] is n
ot part of defined whitelist (skipping transfer from repository [Java.net Repository for Maven 2]).

---

**Affects:** 1.0-beta-3, 1.0-beta-4

**Issue Links:**
- [MNG-4528](https://issues.apache.org/jira/browse/MNG-4528) [regression] mvn deploy ignores proxy settings

- [WAGON-225](https://issues.apache.org/jira/browse/WAGON-225) proxyInfoProvider is never used

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this was a bug fixed in wagon-provider-api 1.0-beta-4, which was not included in Archiva 1.1. See MRM-884 for more information.

**Comment by jira-importer** [comment]
**[Thomas BELOT](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.belot)** commented

Hi Brett,

Thanks for the information.

Can you help me some more : i can't find wagon's download page nor wagon-provider-api 1.0-beta-4

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

http://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-beta-4/

The Archiva team is planning to release an updated version ASAP to address this.
