### ISSUE TITLE
[WAGON-183] sftp:// repository crashes build on failed download

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#769]
**[Stephen Charles Duncan, Jr.](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jrduncans)** opened **[WAGON-183](https://issues.apache.org/jira/browse/WAGON-183?redirect=false)** and commented

When using sftp:// for an internal repository, when a download fails,
an error is thrown, and the build quits, even though the file is a)
available in the central repository, or b) optional (downloaidng
sources using Eclipse plugin).  Previously, when using scp with
another machine, this never happened.
Here's the error on downloading:

$ mvn install
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[INFO] Building Trouble Tickets Portlet
[INFO]    task-segment: [install]
[INFO] ----------------------------------------------------------------------------
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
Downloading: sftp://cdciecm.je.jfcom.mil/var/www/maven2/org/springframework/spring-core/1.2.6/spring-core-1.2.6.pom
No such file
at com.jcraft.jsch.ChannelSftp.throwStatusError(Unknown Source)
at com.jcraft.jsch.ChannelSftp.cd(Unknown Source)
at org.apache.maven.wagon.providers.ssh.SftpWagon.getIfNewer(SftpWagon.java:275)
at org.apache.maven.wagon.providers.ssh.SftpWagon.get(SftpWagon.java:335)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:369)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:282)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:244)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:124)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:3
86)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:351)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:102)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:282)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:309)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:67)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:2
23)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:2
11)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:1
82)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1120)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:369)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:47
2)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.springframework:spring-core

Reason: Error getting POM for 'org.springframework:spring-core' from
the repository: Error occured while downloading 'or
g/springframework/spring-core/1.2.6/spring-core-1.2.6.pom' from the
remote repository:[cdcie] -> sftp://cdciecm.je.jfcom
.mil/var/www/maven2
org.springframework:spring-core:pom:1.2.6

from the specified remote repositories:
cdcie (sftp://cdciecm.je.jfcom.mil/var/www/maven2),
central (http://repo1.maven.org/maven2)

[INFO] ----------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Mon Feb 20 22:10:28 EST 2006
[INFO] Final Memory: 3M/7M
[INFO] ------------------------------------------------------------------------

---
No further details from [WAGON-183](https://issues.apache.org/jira/browse/WAGON-183?redirect=false)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

it seems to happen when the directory doesn't exist, and we try to CD to it.

I'm looking into the jsch api to see whether we can LS that directory first, or something...
