### ISSUE TITLE
[WAGON-191] deploy to scp repository hangs forever

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#780]
**[Ralph Poellath](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rpoellath)** opened **[WAGON-191](https://issues.apache.org/jira/browse/WAGON-191?redirect=false)** and commented

After upgrading from alpha-3 to beta-1, deploy to my scp repository hangs forever (alpha-3 works fine with identical settings).

A thread on maven-users concering this issue starts at
http://marc.theaimsgroup.com/?l=turbine-maven-user&m=112721905414020&w=2

Here's a  thread dump taken while deploy hangs:

---

[INFO] [deploy:deploy]
[INFO] Retrieving previous build number from internal
Full thread dump Java HotSpot(TM) Client VM (1.4.2-54 mixed mode):

"Connect thread maven.example.com session" prio=5 tid=0x005651b0 nid=0x1e20000 runnable [f0c89000..f0c89ac0]
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at com.jcraft.jsch.IO.getByte(Unknown Source)
at com.jcraft.jsch.Session.read(Unknown Source)
at com.jcraft.jsch.Session.run(Unknown Source)
at java.lang.Thread.run(Thread.java:552)

"Signal Dispatcher" daemon prio=10 tid=0x00508210 nid=0x1823a00 waiting on condition [0..0]

"Finalizer" daemon prio=8 tid=0x00506ca0 nid=0x1810800 in Object.wait() [f0a04000..f0a04ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x657178d0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:111)
- locked <0x657178d0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:127)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x00506970 nid=0x1803e00 in Object.wait() [f0983000..f0983ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x65717938> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:429)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:115)
- locked <0x65717938> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00500e30 nid=0x1804600 in Object.wait() [f07fe000..f08002c8]
at java.lang.Object.wait(Native Method)
- waiting on <0x650a5f08> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at java.io.PipedInputStream.read(PipedInputStream.java:229)
- locked <0x650a5f08> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.checkAck(ScpWagon.java:614)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.get(ScpWagon.java:407)
  at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:325)
  at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:256)
  at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:198)
  at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:183)
  at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:130)
  at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:75)
  at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:58)
  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:62)
  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:53)
  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:142)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:357)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:479)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:452)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:438)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:131)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:186)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=5 tid=0x005061f0 nid=0x1804e00 runnable

"VM Periodic Task Thread" prio=10 tid=0x00508150 nid=0x1823600 waiting on condition
"Exception Catcher Thread" prio=10 tid=0x00500f90 nid=0x1804a00 runnable

---

**Issue Links:**
- [MNG-1718](https://issues.apache.org/jira/browse/MNG-1718) deploy to scp repository hangs forever
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

pretty sure this will be fixed now.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

not fixed, see duplicate

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

Same thing when the RH box is the server.

Linux version 2.4.21-15.EL (bhcompile@bugs.build.redhat.com) (gcc version 3.2.3 20030502 (Red Hat Linux 3.2.3-34)) #1 Thu Apr 22 00:27:41 EDT 2004

OpenSSH_3.6.1p2, SSH protocols 1.5/2.0, OpenSSL 0x0090701f

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I was experiencing this, albeit not every time. Haven't seen it since recent fixes. Closed, pending testing.
