### ISSUE TITLE
[WAGON-205] verbose exception can improve debugging user problem

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-wagon#798]
**[Juan F. Codagnone](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juam)** opened **[WAGON-205](https://issues.apache.org/jira/browse/WAGON-205?redirect=false)** and commented

An example of an actual get exception:

Caused by: org.apache.maven.wagon.TransferFailedException: Error occured while downloading from the remote repository:[test-private-repo] -> sftp://localhost/tmp/m2
...
Caused by: No such file
at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:1541)
at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:1207)
at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:587)

It doesnt give you much information unless you know to read the whole stacktrace (in this case you can spot  that is a metadata problem because it apears DefaultRepositoryMetadataManager.java:2309). I propose something like:

Caused by: org.apache.maven.wagon.TransferFailedException: Error occured while downloading `ar/com/test/maven/poms/bare/maven-metadata.xml' from the remote repository:[test-private-repo] -> sftp://localhost/tmp/m2

it can be accomplish  with something like: (but you already know that! ;-)

--- src/main/java/org/apache/maven/wagon/providers/ssh/ScpWagon.java    (revision 290590)
+++ src/main/java/org/apache/maven/wagon/providers/ssh/ScpWagon.java    (working copy)
@@ -565,12 +588,14 @@
}
}

- 

      String msg = "Error occured while downloading from the remote repository:" + getRepository();

+ 

      String msg = "Error occured while downloading `" + resource.getName()

+ 

                 + "' from the remote repository:" + getRepository();
      
         throw new TransferFailedException( msg, e );

  }

  public boolean getIfNewer( String resourceName, File destination, long timestamp )

---

**Attachments:**
- [WAGONSSH-15.diff](https://issues.apache.org/jira/secure/attachment/12720707/WAGONSSH-15.diff) (_700 bytes_)

**Issue Links:**
- [MNG-1131](https://issues.apache.org/jira/browse/MNG-1131) address necessary wagon issues
 (_**"is depended upon by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

looks good to me, can you attach it as a path file? :)

**Comment by jira-importer** [comment]
**[Juan F. Codagnone](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=juam)** commented

sure, here it goes!
